#!/usr/bin/env python3
"""make-winpix.py — bake small planet maps into a JS file as data: URLs.

WHY THIS EXISTS
Module 8's forward window is a software raytracer: it samples planet pixels through a canvas
(getImageData) to paint the surface. Browsers refuse to let a page opened from a file:// URL read
pixels back out of a file:// image — the canvas is "tainted" — so opening the course straight off disk
(the primary install path for a non-specialist) lost the Earth and Moon surfaces entirely.

A data: URL is same-origin by definition, so it does NOT taint the canvas. Baking the maps into JS
therefore makes the window work identically from a file, from our server, or from any static host, with
no CORS involved anywhere.

The size cost is small because the raytracer never needs much: it renders into a buffer at most 340 px
wide and samples an equirectangular map capped at 1024x512. 512x256 is already more detail than the
window can show.

Regenerate after changing the source maps:   python3 tools/make-winpix.py
"""
import base64, io, pathlib, sys
from PIL import Image

ROOT = pathlib.Path(__file__).resolve().parent.parent
TEX  = ROOT / 'public' / 'vendor' / 'textures'
OUT  = ROOT / 'public' / 'winpix.js'

# (key, preferred source, fallback source, width, height)
JOBS = [
    ('earth', 'earth_atmos_2048.jpg', 'earth_schematic.jpg', 512, 256),
    ('moon',  'moon_1024.jpg',        'moon_schematic.jpg',   512, 256),
]

parts, report = {}, []
for key, primary, fallback, w, h in JOBS:
    src = TEX / primary
    used = primary
    if not src.exists():
        src, used = TEX / fallback, fallback
    if not src.exists():
        sys.exit(f'ERROR: neither {primary} nor {fallback} found in {TEX}')
    im = Image.open(src).convert('RGB').resize((w, h), Image.LANCZOS)
    buf = io.BytesIO()
    # quality 72 is indistinguishable at the size the window renders, and keeps the file small
    im.save(buf, 'JPEG', quality=72, optimize=True)
    raw = buf.getvalue()
    parts[key] = 'data:image/jpeg;base64,' + base64.b64encode(raw).decode('ascii')
    report.append(f'  {key:6s} {used:24s} -> {w}x{h}, {len(raw)/1024:5.1f} KB jpeg')

body = ',\n'.join(f"  {k}: '{v}'" for k, v in parts.items())
OUT.write_text(
 "/* winpix.js — GENERATED by tools/make-winpix.py. Do not hand-edit.\n"
 "\n"
 "   Small equirectangular Earth/Moon maps as data: URLs, used ONLY by Module 8's forward-window\n"
 "   raytracer, which must read planet pixels back through a canvas.\n"
 "\n"
 "   Why data: URLs and not the .jpg files in vendor/textures/ — a page opened from a file:// URL\n"
 "   cannot read pixels out of a file:// image (tainted canvas), so opening the course straight off\n"
 "   disk used to lose the planet surfaces. A data: URL is same-origin by definition, so the window\n"
 "   now works identically from a file, from server.js, or from any static host.\n"
 "\n"
 "   512x256 is deliberate: the window renders into a buffer at most 340 px wide, so more detail\n"
 "   could not be seen. The full-resolution maps in vendor/textures/ are still what the 3-D globes\n"
 "   in every module use. */\n"
 "'use strict';\n"
 "window.OA_WINPIX = {\n" + body + "\n};\n", encoding='utf-8')

print('wrote', OUT.relative_to(ROOT), f'({OUT.stat().st_size/1024:.0f} KB total)')
print('\n'.join(report))
