/* Worksheet 6 — Lagrange Points & Complex Orbits.
   Builds on Module 5's cislunar system and four reference frames. Interactive tool tut6.html:
   the five Lagrange points, a 1-D force-balance diagram, an L2 halo orbit, TESS (2:1 resonance),
   and a live fan-release chaos sandbox. Language rule: no fictitious-force jargon anywhere. */
const WORKSHEET = {
  objectives: [
    'why an object at a <b>Lagrange point</b> keeps the <b>same 27.3-day period as the Moon</b>, even though it sits at a different distance from Earth.',
    'how, along the Earth–Moon line, the Moon’s pull <b>cancels part of</b> Earth’s at L1 but <b>adds to</b> it at L2 — so both still match the lunar period.',
    'why <b>L1 and L2 are unstable</b> (a golf ball on a basketball) so spacecraft fly looping <b>halo orbits</b> and nudge often, while <b>L4/L5</b> are stable.',
    'what <b>orbital resonance</b> is, using <b>TESS</b> — a 2:1 lock with the Moon that keeps it stable for years.',
    'why the tangled, time-changing <b>gravity of Earth + Moon + Sun</b> makes many trajectories <b>chaotic</b> — tiny differences blow up — and why that makes cislunar tracking hard.',
  ],

  tutorial: [
    'Until now you have orbited <b>either</b> the Earth <b>or</b> the Moon. Out in cislunar space you orbit <b>both at once</b>. What steers a spacecraft there isn’t a single tidy pull — it’s a <b>complex, ever-changing gravitational landscape</b> made by the Earth and the Moon together (and, more faintly, the Sun, and fainter still the other planets and big asteroids).',
    'Deep inside the Earth’s or the Moon’s Hill sphere, that body is overwhelmingly in charge and everything else is a small nudge — a <b>perturbation</b>. But between them, near the boundary, the two pulls are comparable and the motion gets genuinely intricate. On top of all this, neither body is a perfect sphere: their real shapes and lumpy interiors put tiny extra crinkles in the landscape.',
    { h: 'Lagrange points: matching the Moon’s pace' },
    'In this landscape there are five special spots — the <b>Lagrange points</b>, named for an 18th-century French mathematician — where the combined pull of Earth and Moon lets an object circle the Earth in <b>exactly one lunar month (27.3 days)</b>, the same as the Moon. Because they keep pace with the Moon, they sit at fixed places on the rotating Earth–Moon line. (There’s an analogous set of <b>Earth–Sun</b> Lagrange points, where the period matches Earth’s <b>one-year</b> trip around the Sun.)',
    { analogy: 'Picture a <b>bead on a rigid rod</b> that sweeps around once a month, with Earth at one end and the Moon out along it. The bead is forced to stay on the rod. Slide it to just the right spot and the leftover gravity — Earth’s pull minus or plus the Moon’s — is exactly what’s needed to swing it around with the rod. That balance spot is a Lagrange point.' },
    'How can points at <i>different</i> distances all take 27.3 days? A moonless object closer in (like L1) would normally orbit <b>faster</b> than a month; one farther out (like L2) would orbit <b>slower</b>. The Moon fixes the mismatch. At <b>L1</b> (between Earth and Moon) the Moon pulls <i>outward</i>, partly cancelling Earth, so the pull is gentler and the object slows to a monthly pace. At <b>L2</b> (beyond the Moon) both bodies pull the same way and <i>add</i>, so the stronger pull speeds a would-be-slow object up to a monthly pace. The tool’s force-balance view shows this with arrows.',
    { figure: '<svg viewBox="0 0 640 220" width="640" xmlns="http://www.w3.org/2000/svg"><rect width="640" height="220" fill="#f4f8fc"/>'+
      '<line x1="40" y1="120" x2="600" y2="120" stroke="#9aa7bd" stroke-width="1.5"/>'+
      '<circle cx="70" cy="120" r="20" fill="#2b6fb5"/><text x="70" y="124" font-size="10" fill="#fff" text-anchor="middle">Earth</text>'+
      '<circle cx="470" cy="120" r="11" fill="#b8b2a4"/><text x="470" y="152" font-size="11" fill="#5a6270" text-anchor="middle">Moon</text>'+
      // L1 between (blue inward long, grey outward short)
      '<circle cx="400" cy="120" r="4" fill="#ffcf4d"/><text x="400" y="150" font-size="11" fill="#8a5a00" text-anchor="middle">L1</text>'+
      '<path d="M400 104 l-70 0" stroke="#2b6fb5" stroke-width="2.5" marker-end="url(#ar)"/>'+
      '<path d="M400 104 l30 0" stroke="#b8b2a4" stroke-width="2.5" marker-end="url(#ar)"/>'+
      // L2 beyond (both inward, add)
      '<circle cx="560" cy="120" r="4" fill="#ff8a4d"/><text x="560" y="150" font-size="11" fill="#8a5a00" text-anchor="middle">L2</text>'+
      '<path d="M560 92 l-55 0" stroke="#2b6fb5" stroke-width="2.5" marker-end="url(#ar)"/>'+
      '<path d="M560 92 l-30 0" stroke="#b8b2a4" stroke-width="2.5" marker-end="url(#ar)"/>'+
      '<text x="150" y="40" font-size="12" fill="#2b6fb5">▬ Earth’s pull</text><text x="300" y="40" font-size="12" fill="#8a7f6b">▬ Moon’s pull</text>'+
      '<text x="150" y="200" font-size="12" fill="#5a6270">At L1 the pulls oppose (gentler net); at L2 they add (stronger net) — both give a 27.3-day loop.</text>'+
      '<defs><marker id="ar" markerWidth="8" markerHeight="8" refX="6" refY="4" orient="auto"><path d="M0 0 L7 4 L0 8 z" fill="#333"/></marker></defs></svg>',
      caption: 'Along the Earth–Moon line: at L1 the Moon’s pull points back toward the Moon (outward from Earth), opposing Earth; at L2 both pulls point inward and add. Either way the leftover pull matches a 27.3-day orbit.' },
    { h: 'Stable and unstable balance points' },
    '<b>L4 and L5</b> — sixty degrees ahead of and behind the Moon — are <b>stable</b>: nudge an object and it loops lazily around the point instead of leaving — in the inertial frame it is simply flying a Moon-like 27.3-day orbit that the combined pulls keep herded near the point (L4/L5 are actually gentle <i>hilltops</i> of the co-rotating field, not bowls — the stability lives in the motion, not the terrain), so dust and debris can gather there on their own. <b>L1, L2, and L3</b> are <b>unstable</b> — balancing there is like a <b>golf ball perched on a basketball</b>. A real mission (like the CAPSTONE spacecraft near the Moon) can’t just park; it flies a slow looping <b>halo orbit</b> around the empty point and taps its thrusters now and then to stay. A bonus: a spacecraft this close to the Moon shows the <b>same illuminated phase the Moon does</b> at that moment — same Sun angle, so a full moon means a “full” spacecraft.',
    { h: 'Complex orbits, resonance, and chaos' },
    'Not everything sits at a balance point. <b>TESS</b>, a NASA telescope, rides a stretched orbit locked in a <b>2:1 resonance</b>: it laps the Earth twice for every once the Moon goes around, always meeting the Moon in the same relative spots so the Moon’s tugs cancel out over time instead of building up. That careful bookkeeping keeps it stable for years. But stray from such special paths and the Earth+Moon field turns <b>chaotic</b>: two objects released almost identically drift wildly apart within days. You’ll watch that happen — it’s the deep reason keeping track of things in cislunar space is so hard. (You’ll also recognize the Moon’s <b>tidal lock</b> here — the same face always toward Earth — as one more consequence of these gravitational tugs.)',
  ],

  // The five Lagrange points as a definitions table.
  elements: {
    title: 'The five Earth–Moon Lagrange points',
    cols: ['Point', 'Where it is', 'What’s special'],
    rows: [
      { name:'<b>L1</b>', meaning:'Between Earth and Moon, ~84.9% of the way out (~326,000 km).',
        tool:'Moon’s pull opposes Earth’s → gentler net pull → matches the 27.3-day period. <b>Unstable.</b>' },
      { name:'<b>L2</b>', meaning:'Beyond the Moon, ~116.8% of the Earth–Moon distance (~449,000 km).',
        tool:'Earth + Moon pulls add → stronger net pull → matches 27.3 days. <b>Unstable</b> (halo orbits + station-keeping).' },
      { name:'<b>L3</b>', meaning:'On the far side of Earth, opposite the Moon.',
        tool:'Matches the lunar period on the other side. <b>Unstable</b>; little practical use.' },
      { name:'<b>L4 / L5</b>', meaning:'60° ahead of and behind the Moon along its orbit (equilateral triangle).',
        tool:'Also match 27.3 days — and are <b>stable</b>, so dust and debris can collect there.' },
    ],
    foot: 'There is an analogous set of <b>Earth–Sun</b> Lagrange points, where the matching period is one <b>year</b>. Real sun-watching and deep-space telescopes park near those.',
  },

  parts: [
    { title:'PART A · What makes cislunar space complex', blurb:'You now orbit Earth and Moon together, in an ever-changing gravity landscape.', tasks:['a1'] },
    { title:'PART B · The five Lagrange points', blurb:'Five spots that keep the Moon’s pace — and why.', tasks:['b1','b2','b3'] },
    { title:'PART C · Halo orbits & resonance', blurb:'How real missions live at unstable points, and what a resonance buys you.', tasks:['c1','c2'] },
    { title:'PART D · Chaos: the fan release', blurb:'Six release experiments — the L1 knife-edge, stable tadpoles at L4, lunar slingshots, retrograde parking, the free-return figure-8, and Earth’s temporary minimoons — and why tracking out here is hard.', tasks:['d1','d1t','d1b','d1c','d1d','d1e','d1m','d2'] },
    { title:'PART E · How to orbit around nothing', blurb:'The libration zoo: non-Keplerian orbits around an empty point, set by a single number. Maximum weirdness.', tasks:['e1'] },
  ],

  summary: [
    'Cislunar trajectories are set by the <b>combined, time-changing gravity of Earth + Moon</b> (with the Sun and others as smaller nudges, and even the bodies’ non-spherical shapes adding crinkles).',
    'The five <b>Lagrange points</b> are spots where Earth + Moon together give an object the <b>Moon’s own 27.3-day period</b>, so it holds station on the rotating Earth–Moon line.',
    'At <b>L1</b> the Moon’s pull opposes Earth’s (gentler net pull); at <b>L2</b> the two pulls add (stronger net pull). Either way the leftover pull is exactly what a 27.3-day loop needs — so “balance” does <b>not</b> mean zero pull.',
    '<b>L1/L2/L3 are unstable</b> (a golf ball on a basketball) — missions fly small looping <b>halo orbits</b> and nudge often. <b>L4/L5 are stable</b>, so dust and debris can gather there.',
    'There are analogous <b>Earth–Sun</b> Lagrange points with a <b>one-year</b> period.',
    'A spacecraft near the Moon shows the <b>same illuminated phase</b> as the Moon at that moment (same Sun angle).',
    'The Moon is <b>tidally locked</b> — one face always toward Earth — because gravity locked its spin to its orbit. So the Sun sweeps around it once a (synodic) month — that moving sunlight is what drives the phases.',
    '<b>Orbital resonance</b> (e.g. TESS’s 2:1 lock with the Moon) can make a complex orbit <b>stable</b> by arranging the Moon’s repeated tugs to cancel over time.',
    'Away from such special paths, Earth+Moon gravity is <b>chaotic</b>: near-identical starts diverge within days. That sensitivity is why long-term cislunar tracking is genuinely hard.',
    'A close lunar pass acts as a <b>gravitational slingshot</b>: it can fling an object in almost any direction — even far beyond Earth’s <b>Hill sphere</b> (~1.5 million km), where the Sun’s gravity takes over and it never returns.',
    '<b>Stability is real estate</b>: L4/L5 and distant retrograde orbits (DROs) hold objects for months to years with no fuel; L1/L2 shed everything without station-keeping; and a <b>free-return figure-8</b> comes home from the Moon on gravity alone.',
  ],

  resources: [
    { t:'Lagrange point — Wikipedia', u:'https://en.wikipedia.org/wiki/Lagrange_point' },
    { t:'Halo orbit — Wikipedia', u:'https://en.wikipedia.org/wiki/Halo_orbit' },
    { t:'CAPSTONE (near-rectilinear halo orbit)', u:'https://en.wikipedia.org/wiki/CAPSTONE_(spacecraft)' },
    { t:'Lunar Gateway — the southern NRHO it will fly', u:'https://en.wikipedia.org/wiki/Lunar_Gateway', note:'halos come in mirror-image northern/southern families; Gateway uses a southern one' },
    { t:'TESS (Transiting Exoplanet Survey Satellite) — 2:1 lunar resonance', u:'https://en.wikipedia.org/wiki/Transiting_Exoplanet_Survey_Satellite' },
    { t:'Orbital resonance — Wikipedia', u:'https://en.wikipedia.org/wiki/Orbital_resonance' },
    { t:'Tidal locking (why one face) — Wikipedia', u:'https://en.wikipedia.org/wiki/Tidal_locking' },
    { t:'Three-body problem & chaos — Wikipedia', u:'https://en.wikipedia.org/wiki/Three-body_problem' },
    { t:'Jacobi constant (the one parameter of the family) — Wikipedia', u:'https://en.wikipedia.org/wiki/Jacobi_integral', note:'the conserved rotating-frame energy that labels each libration orbit' },
    { t:'Lissajous orbit — Wikipedia', u:'https://en.wikipedia.org/wiki/Lissajous_orbit', note:'the never-closing quasi-periodic cousins of halo orbits' },
    { t:'Lyapunov orbit (the planar base of the family) — Wikipedia', u:'https://en.wikipedia.org/wiki/Lyapunov_orbit' },
    { t:'Why halos are non-Keplerian: the CR3BP — Wikipedia', u:'https://en.wikipedia.org/wiki/Three-body_problem#Circular_restricted_three-body_problem' },
    { t:'Gravity assist (the slingshot maneuver) — Wikipedia', u:'https://en.wikipedia.org/wiki/Gravity_assist', note:'how a flyby trades a bit of the planet/Moon’s orbital energy for spacecraft speed — the physics behind the lunar-scatter demo' },
    { t:'Specific orbital energy (bound vs. unbound) — Wikipedia', u:'https://en.wikipedia.org/wiki/Specific_orbital_energy', note:'the ε = v²/2 − μ/r test the tool uses to flag escaping objects' },
    { t:'Hyperbolic trajectory (escape orbits) — Wikipedia', u:'https://en.wikipedia.org/wiki/Hyperbolic_trajectory' },
    { t:'Butterfly effect / sensitive dependence on initial conditions — Wikipedia', u:'https://en.wikipedia.org/wiki/Butterfly_effect', note:'why two near-identical launches end up with completely different fates' },
    { t:'Cislunar space domain awareness (AFRL / SDA overview)', u:'https://en.wikipedia.org/wiki/Cislunar_space', note:'why tracking and keeping custody of objects out here is a frontier problem' },
    { t:'Joseph-Louis Lagrange — Wikipedia', u:'https://en.wikipedia.org/wiki/Joseph-Louis_Lagrange' },
  ],

  tasks: [
    // ---- PART A ----
    { id:'a1', title:'One landscape, two attractors',
      teach:[
        'In Module 5 you saw the tug-of-war: near the Earth, Earth wins; near the Moon, the Moon wins. Now zoom into the <b>space between</b>, where their pulls are comparable. Here there’s no single “center” to orbit — a spacecraft moves through a <b>combined gravity landscape</b> shaped by both bodies at once, and that landscape <b>turns</b> as the Moon goes around.',
        'The Sun adds a gentler influence, and even the other planets and big asteroids nudge things at a tiny level. And because Earth and the Moon aren’t perfect spheres, their real shapes wrinkle the landscape a little more. The upshot: cislunar trajectories can be far richer than the clean ellipses of the earlier modules.',
      ],
      predict:'Before you look: out between Earth and the Moon, do you expect an object’s path to be a simple repeating ellipse like the ones you built earlier — or something more complicated?',
      do:'Open the tool on the <b>five Lagrange points</b> scenario. Switch to the <b>Earth–Moon rotating (synodic)</b> frame and speed time up, then flip to <b>ECI</b> and back to feel how the whole landscape turns with the Moon.',
      observe:'in the rotating frame the Earth, Moon, and the five marked points all hold still; in ECI the Moon (and the points) sweep around once a month.',
      think:[
        'Which single frame makes this system easiest to reason about, and why?',
        'What’s the biggest influence on a spacecraft sitting halfway to the Moon — and what are the smaller “perturbations”?',
        'Why does it help that the Lagrange points hold still in the rotating frame?',
      ],
      quiz:{ q:'Out in cislunar space (between Earth and Moon), what determines a spacecraft’s trajectory?',
        opts:['Only the Earth’s gravity','The combined, ever-changing gravity of Earth and Moon together (plus smaller nudges from the Sun and others)',
              'Only the Moon’s gravity','No gravity at all — it drifts in a straight line'],
        a:1, why:'Correct — between the two bodies neither dominates; the path is set by their combined field, which itself turns as the Moon orbits.',
        feedback:['Earth dominates only close in; out here the Moon matters too.','','The Moon dominates only inside its Hill sphere; out here Earth still pulls hard.','Gravity is very much in play — that’s what makes the motion complex.'] } },

    // ---- PART B ----
    { id:'b1', title:'Five points that keep the Moon’s pace',
      teach:[
        'Scattered through this landscape are five special spots — the <b>Lagrange points</b> — where the combined pull of Earth and Moon lets an object circle Earth in <b>exactly one lunar month</b>. Because they keep pace with the Moon, they’re fixed on the rotating Earth–Moon line: in the synodic frame they never move.',
        'Three of them (<b>L1, L2, L3</b>) sit right on the Earth–Moon line; two (<b>L4, L5</b>) sit 60° ahead of and behind the Moon, forming equal-sided triangles with Earth and Moon. The definitions table above lists all five.',
      ],
      predict:'A point closer to Earth than the Moon would, on its own, want to orbit FASTER than a month; a point farther out would want to orbit SLOWER. How do you think all five points can still share the Moon’s 27.3-day period?',
      do:'In the <b>five Lagrange points</b> scenario, switch to the synodic frame. Identify L1, L2, L3 on the line and L4/L5 off to the sides. Speed up time: the ▲ markers hold their geometry fixed as the whole system turns underneath — which the frozen frame makes look perfectly still. Flip to <b>ECI</b> for a moment to see the same pattern sweep around once a month.',
      observe:'the five ▲ markers keep their pattern locked to the rotating Earth–Moon line — an object placed at any of them would circle Earth at the Moon’s pace, holding station on that line.',
      think:[
        'Which points are on the Earth–Moon line, and which are off it?',
        'L4 and L5 make equal-sided triangles with Earth and the Moon — why might that symmetry matter?',
        'What would it mean, physically, for an object to “hold still” in this rotating frame?',
      ],
      quiz:{ q:'What do all five Lagrange points have in common?',
        opts:['They have zero gravity','An object placed there orbits Earth with the same 27.3-day period as the Moon, so it holds station on the rotating Earth–Moon line',
              'They are all equally far from Earth','They are the only places a spacecraft can survive'],
        a:1, why:'Correct — that shared lunar period is the defining feature; it’s why they sit still in the frame that turns with the Moon.',
        feedback:['Gravity is strong there — it’s balanced to give a specific period, not zero.','','They sit at very different distances (L1 ~326,000 km, L2 ~449,000 km).','Spacecraft thrive in many orbits; L-points are just special ones.'] } },
    { id:'b2', title:'The force balance at L1 and L2',
      teach:[
        'Here’s the crux — and it answers the puzzle from the last exercise. Consider a <b>bead threaded on a rigid rod</b> that sweeps around once a month, Earth at the center and the Moon out along it. The bead is <i>constrained</i> to the rod (that’s the picture the “release on the line” demo quietly assumes). Along that rod, gravity has to supply exactly the pull needed to swing the bead around with the rod.',
        'At <b>L1</b>, between Earth and Moon, the Moon lies farther out, so its pull points <i>outward</i> — back toward the Moon, opposing Earth. The two partly cancel, leaving a <b>gentler</b> net inward pull. That’s perfect for a point this close, which would otherwise be dragged around too fast. At <b>L2</b>, beyond the Moon, both bodies pull the same way and <b>add</b>, giving a <b>stronger</b> pull — perfect for a point this far out, which would otherwise lag behind. So “balance” never means zero pull; it means the <i>leftover</i> pull matches a 27.3-day loop.',
      ],
      predict:'At L1, the Moon sits farther from Earth than the object does. Which way do you think the Moon’s pull points — toward Earth (adding to Earth’s pull) or away from Earth (opposing it)?',
      do:'Open the <b>Force balance at L1 · Moon · L2</b> scenario. Compare the arrows: at L1, note the Moon’s arrow pointing back toward the Moon (opposing Earth); at L2, note both arrows pointing the same way.',
      observe:'at L1 the Moon’s pull opposes Earth’s (net pull is reduced); at L2 the two pulls add (net pull is increased) — yet both yield the same 27.3-day period.',
      think:[
        'At L1, is the net inward pull bigger or smaller than Earth’s pull alone? What about at L2?',
        'Why does a point closer in need a <i>gentler</i> pull to take a full month, while a point farther out needs a <i>stronger</i> one?',
        'Does “balance point” mean there is no net pull on the object? (Careful!)',
      ],
      quiz:{ q:'At the L1 point (between Earth and the Moon), how does the Moon’s gravity affect the net pull on an object there?',
        opts:['It adds to Earth’s pull, making the net pull stronger','It points back toward the Moon (opposing Earth), making the net inward pull gentler',
              'It has no effect','It cancels Earth’s pull exactly, leaving zero net pull'],
        a:1, why:'Correct — at L1 the Moon is farther out, so it pulls outward and partly cancels Earth. The gentler leftover pull is just right for a 27.3-day loop at that closer-in distance.',
        feedback:['That’s L2, where both pulls point inward and add.','','The Moon’s pull is a big part of the story at L1.','It only partly cancels — there’s still a real inward pull, which is what carries the object around.'] } },
    { id:'b3', title:'Stable vs. unstable balance points',
      teach:[
        'Not all balance points are equal. <b>L4 and L5</b> (60° ahead of and behind the Moon) are <b>stable</b>: give an object there a small nudge and it doesn’t leave — it loops lazily <i>around</i> the point, so dust and debris naturally accumulate there. <b>L1, L2, and L3</b> are <b>unstable</b> — parking there is like balancing a <b>golf ball on top of a basketball</b>: dead center it holds, but the slightest push and it rolls off.',
        'That instability is why you can’t just leave a spacecraft sitting at L1 or L2. It has to fly a slow looping path <i>around</i> the empty point — a <b>halo orbit</b> — and fire its thrusters occasionally to stay near it. You’ll see one next.',
        'Now the twist that surprises everyone: on the gravity landscape, L4/L5 are <b>HILLTOPS, not bowls</b>. Their stability does NOT come from the terrain — the landscape only scores <i>positions</i>, and <b>stability is a property of trajectories</b>. An object near L4 isn’t a ball resting on a surface; it’s <i>moving</i>, flying an ordinary <b>27.3-day orbit around Earth</b> just like the Moon’s, sixty degrees ahead — and the <b>combined pulls of Earth and Moon</b> keep that orbit gently breathing near the point instead of diverging. Switch to the <b>ECI (inertial) frame</b> and that’s exactly what you’ll see: nothing balances on a hill, something simply <i>orbits</i>. Watched from the co-rotating view, the same ordinary orbit appears as a slow loop <i>around</i> the summit — the <b>tadpole orbits</b> you’ll fly in Part D.',
      ],
      predict:'If L1 and L2 are unstable like a golf ball on a basketball, what do you think a real spacecraft has to do to “stay” at one of them?',
      do:'Back in the <b>five Lagrange points</b> scenario, switch to the <b>synodic</b> frame and turn on the <b>gravity landscape</b> checkbox: a wireframe surface of the co-rotating gravity field (<b>Earth + Moon only</b> — the Sun is outside this module’s model; its differential pull is ~1% of Earth’s at the Moon’s distance, and it only takes charge out near the Hill sphere, ~1.5 M km). Find the deep funnels (Earth, Moon), the <b>saddle passes</b> at L1/L2/L3, and the gentle <b>hilltops</b> at L4/L5 — then remember the landscape only scores <i>positions</i>: everything out here is <b>orbiting</b>, not resting. Flip to <b>ECI</b> and check what an object at L4 is really doing. (Part D lets you actually run that experiment.)',
      observe:'L4/L5 forgive a nudge (stable); L1/L2/L3 do not (unstable) — so real missions there never simply sit still. On the landscape, L1 is visibly a mountain pass between two basins — and L4/L5 are hilltops whose stability lives in the <i>trajectories</i>: motion under the combined Earth + Moon pulls loops around the point (in ECI, an ordinary Moon-like orbit 60° ahead), rather than sliding off the terrain.',
      think:[
        'Why might dust or small debris pile up at L4/L5 but not at L1/L2?',
        'The landscape shows L4/L5 as HILLTOPS — so where does their stability actually come from?',
        'What’s the trade-off of using an unstable point like L2 anyway (why bother)?',
        'How is “balancing a golf ball on a basketball” a good picture of an unstable equilibrium?',
      ],
      quiz:{ q:'Which Lagrange points are STABLE (a nudged object stays nearby, looping around the point)?',
        opts:['L1 and L2','L3 only','L4 and L5','All five are stable'],
        a:2, why:'Correct — only L4 and L5 are stable; L1, L2, and L3 are unstable, so missions there fly halo orbits and nudge to stay.',
        feedback:['L1 and L2 are the classic UNSTABLE points.','L3 is also unstable.','','L1/L2/L3 are unstable — a nudge there grows.'] } },

    // ---- PART C ----
    { id:'c1', title:'A near-rectilinear halo orbit (NRHO)',
      teach:[
        'Since you can’t sit still at an unstable point, the trick is to <b>loop around it</b>. A <b>halo orbit</b> is a three-dimensional loop that circles an empty Lagrange point; with occasional small thruster nudges a spacecraft can ride it for years. The exotic member of the family is the <b>near-rectilinear halo orbit (NRHO)</b> — the real path NASA’s <b>CAPSTONE</b> flew and the one the crewed <b>Gateway</b> station will use.',
        'An NRHO is dramatically stretched and nearly <b>vertical</b>: the spacecraft <b>skims low over one lunar pole</b> (a few thousand km) and then swings <b>far out over the other pole</b> (tens of thousands of km), taking about <b>6.5 days</b> per loop. That shape is chosen on purpose — it stays in near-constant sunlight and keeps an almost unbroken radio line to Earth, while costing very little fuel to hold.',
        'Notice it is <b>lopsided about the Moon’s orbital plane</b> — close on one side, far on the other. That may feel wrong: the gravity field <i>is</i> mirror-symmetric top-to-bottom, so shouldn’t the orbit be too? No. The field’s symmetry means halos come in mirror-image <b>pairs</b> — a “northern” one and a “southern” one — but each individual orbit picks a side. (It’s like a symmetric double-well: the pair of low points is symmetric, yet a ball settles into <i>one</i> well.) Gateway will fly a southern NRHO; its mirror twin is equally valid. The orbit <i>is</i> still perfectly symmetric — just about the plane through the <b>Earth–Moon line and the poles</b>, not the orbital plane.',
        'One neat consequence of being near the Moon: the spacecraft is lit by the Sun from the <b>same angle the Moon is</b>, so it shows the <b>same phase</b> — near full moon it’s a “full” spacecraft, near new moon it’s dark. Same Sun, same geometry.',
      ],
      predict:'A spacecraft can’t rest at an unstable Lagrange point. Before you watch: what shape of motion do you think lets it stay <i>near</i> the point without sitting exactly on it? And do you expect the loop to sit evenly above and below the Moon’s orbital plane, or lopsided to one side?',
      do:[
        'Open the <b>near-rectilinear halo (NRHO)</b> scenario. Watch a few full loops and pay attention to the <b>pace</b> of the spacecraft — where does it move fast, and where does it seem to hang?',
        'Use the <b>arrow keys to rotate the view</b> (←/→ swing around, ↑/↓ tip over the pole). Find the edge-on angle where you can see the loop is <b>lopsided about the orbital plane</b> — close on one side, far on the other — not evenly split.',
        'Flip through the four reference frames, then open <b>⊞ Compare all 4 frames (2×2)</b>: the same tall loop looks completely different held still against the stars (ECI), against the Earth–Moon line (synodic), and centred on the Moon (MCI).',
      ],
      observe:'the spacecraft never sits on the point — it rides a tall, lopsided loop; it <b>whips through the close pole pass in hours but lingers for days out at the far end</b>, so it is actually far from the Moon almost the whole time; rotating the view shows the loop is one-sided about the orbital plane, and the 2×2 view shows how differently it reads in each frame.',
      think:[
        'Why loop <i>around</i> the point instead of sitting on it?',
        'Here’s the counterintuitive part: this is called a <b>lunar</b> orbit, yet where does the spacecraft spend <b>most of its time</b> — right over the Moon, or far away from it? Why? (Recall Molniya from Module 3: fast at the close point, slow at the far point.)',
        'The loop isn’t mirror-symmetric about the orbital plane — yet the gravity field is. How can a symmetric field allow a one-sided orbit? (Think of the pair: is there a mirror-image halo on the other side?)',
        'Which of the four frames made the halo’s shape easiest to understand, and why?',
      ],
      quiz:{ q:'Why does a spacecraft near an unstable Lagrange point fly a looping “halo orbit” (like the NRHO) instead of parking at the point?',
        opts:['The point is too far to reach','The point is unstable — sitting there is like balancing a golf ball on a basketball — so it loops around and nudges to stay near',
              'Halo orbits use no fuel at all','The Moon blocks the point'],
        a:1, why:'Correct — because the point is unstable, the spacecraft can’t rest there; a halo loop plus occasional small burns keeps it in the neighborhood.',
        feedback:['It’s reachable — CAPSTONE did it.','','It still needs occasional station-keeping nudges; the halo just makes them small.','The point isn’t blocked; the issue is instability.'] } },
    { id:'c2', title:'TESS and orbital resonance',
      teach:[
        'Some complex orbits stay stable not by balancing forces but by clever <b>timing</b>. NASA’s <b>TESS</b> telescope rides a stretched, high orbit in a <b>2:1 resonance</b> with the Moon: it goes around Earth <b>twice</b> for every <b>once</b> the Moon does. Because it always returns to the same places relative to the Moon, the Moon’s repeated tugs <b>average out</b> instead of piling up and wrecking the orbit — so TESS holds its path for years with almost no fuel.',
        'Resonance is a recurring trick in the solar system (it also sculpts the asteroid belt and Saturn’s rings). TESS is a clean, modern cislunar example — and a good one to view in different frames, since the same path looks strikingly different depending on what you hold still.',
      ],
      predict:'TESS circles Earth twice for every one lunar orbit, always meeting the Moon in the same spots. Do you think the Moon’s repeated tugs will build up and wreck the orbit, or cancel out over time? And before you switch frames: which viewpoint do you think will make the 2:1 pattern most obvious?',
      do:[
        'Open the <b>TESS</b> scenario, speed up time, and count laps: the dot rings Earth <b>twice</b> for every one lap the Moon makes.',
        'Switch to the <b>Earth–Moon rotating (synodic)</b> frame and keep watching the dot: every lunar month it meets the Moon with the <b>same relative geometry</b> — that repeating rendezvous is the 2:1 lock.',
        'Use the <b>arrow keys to rotate</b> the view and confirm TESS’s orbit is <b>tilted out of the Moon’s plane</b> (it’s an inclined HEO, not co-planar).',
      ],
      observe:'TESS laps Earth exactly twice per lunar orbit, so it returns to the same geometry relative to the Moon each cycle — easiest to catch in the synodic frame, where the Moon holds still while the dot repeats its rendezvous — and rotating shows the orbit is inclined, not in the Moon’s plane.',
      think:[
        'What does “2:1” literally count — orbits of what, versus what?',
        'Why does always meeting the Moon in the same places keep the orbit stable?',
        'Why does the synodic frame — where the Moon holds still — make the repeating 2:1 rendezvous easiest to catch?',
        'How is holding the right frame still (to reveal a repeating pattern) like the resonance itself — a matter of matching rhythms?',
      ],
      quiz:{ q:'TESS is in a 2:1 resonance with the Moon. What does that mean, and why does it help?',
        opts:['It orbits twice as fast as light; it avoids the Moon',
              'It laps the Earth twice for each single lunar orbit, always meeting the Moon in the same spots so the Moon’s tugs average out — keeping the orbit stable for years',
              'It stays exactly at L2','It never comes near the Moon'],
        a:1, why:'Correct — the 2:1 timing makes the Moon’s repeated pulls cancel over each cycle instead of accumulating, so the orbit is stable with almost no fuel.',
        feedback:['Nothing orbits near light speed; 2:1 is a ratio of orbital periods.','','TESS is on a resonant HEO, not at a Lagrange point.','It does approach the Moon’s distance — the resonance is what keeps that safe.'] } },

    // ---- PART D ----
    { id:'d1', title:'The knife-edge at L1',
      teach:[
        'You learned in Part B that L1 is an <b>unstable</b> balance point — a ball on a saddle. Now feel what that means. The <b>⚖ L1 knife-edge</b> release drops <b>seven objects exactly at L1</b>, all riding the rotating Earth–Moon line, differing only by tiny velocity kicks — <b>at most 8 m/s, bicycle pace</b>. You could not tell them apart by eye.',
        'For days, nothing happens: the balance is real, and they hover together. Then the saddle wins. Which way each object falls is decided entirely by its imperceptible kick: toward the Moon, toward Earth, or holding out longest with no kick at all. Even the <b>un-kicked</b> one leaves after ~3 weeks — at an unstable equilibrium, disturbances too small to measure (in the sim, literally the computer’s round-off) are eventually enough. Nothing stays at L1 without station-keeping.',
      ],
      predict:'Seven objects at the same point, same speed to within 8 m/s. Will they still be together after two weeks? Where do you think they’ll end up?',
      do:[
        'Open the <b>Fan release</b> scenario, pick <b>⚖ L1 knife-edge</b>, and press <b>▶ release</b>. Watch in the <b>synodic (co-rotating)</b> frame, where L1 stands still.',
        'For the first days they sit as one dot on the ▲ L1 marker. Be patient (or tap <kbd>.</kbd> to speed up) — then watch them peel away one by one.',
        'Track the fates: some fall to the <b>Moon</b> (~day 8–9), some fall <b>home toward Earth</b> (~day 11–14), the out-of-plane one lasts to ~day 18, the un-kicked one to ~3 weeks. The “current scatter” readout measures the blow-up live.',
      ],
      observe:'objects that started indistinguishably close hover together for days, then diverge to completely different fates — the saddle amplifies any difference, however small.',
      think:[
        'How long did the group LOOK stable before the first one left?',
        'An 8 m/s kick is about riding-a-bike speed. Why does something that small decide between “falls to the Moon” and “falls home”?',
        'What does this imply for a real spacecraft parked near L1 — can it just sit there?',
      ],
      quiz:{ q:'Seven objects are released exactly at L1 with kicks of at most 8 m/s. What does the knife-edge release show?',
        opts:['They all stay at L1 — it’s a balance point, after all',
              'They hover together for days, then tiny kick differences decide entirely different fates (Moon, Earth, or holding out) — L1 is an unstable equilibrium',
              'They immediately fly apart in random directions','The kicks are too small to matter, so they drift as one group forever'],
        a:1, why:'Correct — the balance at L1 is real but unstable: it holds briefly, then amplifies even imperceptible differences into completely different outcomes. That’s why L1/L2 missions budget fuel for station-keeping.',
        feedback:['The balance is real but UNSTABLE — nothing stays without station-keeping.','','The instability takes days to develop — at first the balance genuinely holds.','Small differences are exactly what an unstable point amplifies.'] } },
    { id:'d1t', title:'Tadpoles at L4 — the stable pocket',
      teach:[
        'Now run the identical experiment at <b>L4</b>, 60° ahead of the Moon — where Part B promised <b>stability</b>. The <b>🐸 L4 tadpoles</b> release uses kicks up to <b>30 m/s</b>, nearly four times what doomed the L1 set.',
        'The result is completely different: instead of falling away, the objects <b>librate</b> — they trace lazy closed loops around L4, weeks per lap, shaped like tadpoles in the rotating frame. Bigger kick, bigger loop; but they stay. This is why <b>Trojan asteroids</b> have camped at Jupiter’s L4/L5 for billions of years, with nobody station-keeping them. One object in the set was kicked <b>50 m/s</b> — and it breaks out and wanders off along the Moon’s orbit: the stable pocket is real, but it has a <b>finite rim</b>.',
      ],
      predict:'Same experiment, but at L4 with kicks up to 4× bigger. Based on Part B, what do you expect this time?',
      do:[
        'Pick <b>🐸 L4 tadpoles</b> and press <b>▶ release</b>. Stay in the <b>synodic</b> frame — libration is invisible in any other view.',
        'Speed up with <kbd>.</kbd> and watch for weeks of sim time: the objects loop around the L4 marker without leaving.',
        'Find the <b>red</b> object — the 50 m/s one. Watch it leave the tadpole region and drift along the Moon’s orbit (it makes a startlingly close pass by the Moon).',
      ],
      observe:'kicks that would have doomed the L1 set just set the size of a closed libration loop around L4 — only the 50 m/s outlier escapes the pocket.',
      think:[
        'The L1 set scattered in days; the L4 set is still together after months. What single word explains the difference?',
        'Where does a “tadpole loop” exist — in the inertial view, or only in the rotating frame? Why?',
        'If you had to park a satellite in cislunar space for a decade with no fuel, where would you put it?',
      ],
      quiz:{ q:'The same kicks (and bigger) that scattered the L1 release only make objects at L4 loop in place. Why?',
        opts:['L4 has stronger gravity that holds them down',
              'L4 is a STABLE equilibrium: displaced objects librate in closed tadpole loops instead of falling away — the pocket only fails past a finite rim (the 50 m/s object escapes)',
              'The Moon shields L4 objects from Earth’s pull','It’s a coincidence of this particular release'],
        a:1, why:'Correct — stability means displacements oscillate instead of growing. Same physics as Jupiter’s Trojan asteroids: billions of years parked at L4/L5, no station-keeping.',
        feedback:['Gravity is not stronger there — the STABILITY of the balance is what differs.','','Nothing shields gravity; the geometry of the co-rotating balance does the work.','It’s systematic — every kick up to 30 m/s librates; only the 50 m/s one exceeds the rim.'] } },
    { id:'d1b', title:'Lunar scatter — slingshots and escape',
      teach:[
        'The knife-edge and tadpole releases never left the Earth–Moon neighborhood. Now launch a fan of objects on a <b>transfer orbit whose far point just reaches the Moon</b> — spread slightly in aim, timing and <b>out of the orbital plane</b>. They first <b>coast up one clean arc</b> for about nine days, then all arrive near the Moon in quick succession. When an object passes <b>close to the Moon</b>, the Moon’s gravity swings it hard — a <b>gravitational slingshot</b> (the same trick real missions like the Voyagers used to pick up speed). A near-miss can whip an object off in almost any direction; a direct hit ends the trip.',
        'Here’s the striking part: a slingshot can hand an object <b>so much extra speed</b> that it is flung far beyond Earth’s <b>Hill sphere</b> — the ~1.5-million-km bubble inside which Earth’s gravity, not the Sun’s, is in charge. Past that line, in the real Solar System, the Sun takes over and the object never comes back. In this run the <b>yellow</b> object skims about <b>300 km above the lunar surface</b> — Apollo-8 altitude — and gets thrown onto a ~4-million-km orbit. Whether that happens is exquisitely sensitive to the exact aim: the <b>red</b> object, aimed only slightly differently, instead whips a tight <b>hairpin</b> around the far side and stays.',
        'The tool tallies a <b>“flung away so far”</b> count: objects that are either formally unbound (orbital energy ≥ 0) or carried beyond the Hill sphere.',
      ],
      predict:'Seven objects on nearly-identical transfer orbits toward the Moon. Every one makes a close pass. <b>Predict first:</b> how many of the seven get <b>flung away</b> versus stay looping in the system? Write down your guess.',
      do:[
        'Open the <b>Fan release</b> scenario and pick <b>🌙 lunar scatter</b>, then press <b>▶ release</b>. They <b>coast up one clean arc together</b> (~9 days) before reaching the Moon.',
        '<b>Before they arrive, switch to the Moon-centered inertial (MCI) frame</b> — that puts the camera on the Moon, so each flyby draws its true shape: a clean gravity-bent hyperbolic swing past the Moon. (In Earth-centered views the Moon itself moves during the encounter and the geometry is much harder to read.)',
        'Slow down with <kbd>,</kbd> as they close in and watch each pass: the <b>red</b> hairpin around the far side (~1.4 lunar radii), the <b>yellow</b> 300-km skim, and the wider deflections out to ~13 lunar radii. Every turn is the Moon <i>pulling</i>, never pushing.',
        'Speed back up and let it run for weeks of sim time. Watch the <b>“flung away so far”</b> readout — a green banner announces the first object past the Hill sphere.',
      ],
      observe:'all seven make a close lunar pass, then split fates: most stay looping, but the deepest skim is flung past Earth’s Hill sphere — and in MCI each swing is a clean pull-around, nothing ever bounces.',
      think:[
        'How close did your prediction come to the actual tally of flung-away vs. staying?',
        'What gives an escaping object its extra speed — where does that energy come from? (Hint: the Moon is moving.)',
        'Why can two objects launched only a few degrees apart end up with completely different fates?',
        'How is this the same physics a mission uses to get a “free” speed boost from a flyby?',
      ],
      quiz:{ q:'In the lunar-scatter release, one object gets “flung away.” What does that mean, and how did it happen?',
        opts:['Its tracking data was lost, so we can’t label it',
              'A grazing lunar flyby (a gravity assist) threw it far past Earth’s Hill sphere, where the Sun’s gravity dominates — in reality it never comes back',
              'It ran out of fuel and drifted off','The Moon captured it into lunar orbit'],
        a:1, why:'Correct — the Moon’s slingshot supplies the energy: a deep flyby hurls the object beyond the ~1.5-million-km Hill sphere, out where the Sun, not Earth, is in charge.',
        feedback:['“Flung away” is a physical outcome (energy/distance), not a data problem.','','These objects have no engines — the Moon’s slingshot supplies the energy.','Capture is the opposite outcome; this object leaves rather than settling into lunar orbit.'] } },
    { id:'d1c', title:'See the scatter in 3-D — rotate for the out-of-plane view',
      teach:[
        'Seen from straight above (the default top-down view), the scattering looks like it happens in a flat plane — but it doesn’t. Each object was launched with a slightly <b>different tilt out of the orbital plane</b>, so after the slingshot their paths splay out in <b>all three dimensions</b>, above and below the Moon’s orbit. The flat view hides that entirely.',
        'This is exactly the trap real trackers fall into: a single camera angle (or a single sensor) flattens a 3-D reality into 2-D, and two objects that look like they’re in the same place can actually be tens of thousands of kilometres apart <b>out of the plane</b>. Rotating your viewpoint is the cheapest way to recover that missing dimension — and it’s why cislunar surveillance wants observers at more than one vantage point.',
        'The <b>arrow keys tilt and spin the camera</b> (←/→ swing around, ↑/↓ tip up and over the pole). Give the scene a good tumble while the objects are scattering and the out-of-plane structure jumps out.',
      ],
      predict:'The top-down view makes the scatter look flat. Before you rotate: do you expect the seven paths to actually lie in one plane, or to spread <b>above and below</b> the Moon’s orbit? By roughly how much — hundreds of km, or tens of thousands?',
      do:[
        'Run the <b>🌙 lunar scatter</b> release again and let the objects reach the Moon and begin scattering.',
        'Now hold the <b>← and → arrow keys</b> to swing the camera around the side, then <b>↑ / ↓</b> to tip the view up over the pole — watch the trails lift off the flat plane into a 3-D spray. (Mouse: shift-drag or right-drag rotates; wheel zooms; <kbd>R</kbd> resets the view.)',
        'Find the edge-on angle where the orbital plane looks like a thin line — the out-of-plane objects clearly stand off it, above and below.',
        'For a second perspective, open the <b>⊞ Compare all 4 frames (2×2)</b> view and rotate one panel independently while the others hold still — the same scatter, read from four viewpoints at once.',
      ],
      observe:'the paths are genuinely three-dimensional: rotating the view reveals objects arcing well above and below the Moon’s orbital plane, spread that was completely invisible from straight overhead.',
      think:[
        'How much did rotating the view change your sense of where the objects actually are?',
        'If you only ever saw the top-down view, what mistake might you make about two objects that appear to overlap?',
        'Why would having <b>two</b> observers at different angles beat one, for pinning down a cislunar object’s true position?',
        'The launch tilts were tiny — why does a small out-of-plane nudge grow into a large out-of-plane spread after the Moon flyby?',
      ],
      quiz:{ q:'Rotating the camera during the lunar-scatter release shows that the objects’ paths are…',
        opts:['exactly in one flat plane — the tilt makes no difference',
              'spread in all three dimensions (well above and below the Moon’s orbit), which the top-down view hid',
              'always pointing straight at Earth','identical, just drawn at different sizes'],
        a:1, why:'Correct — the small out-of-plane launch tilts, amplified by the flyby, splay the paths into a true 3-D spray; only rotating the view (or a second vantage point) reveals it.',
        feedback:['They’re not planar — that’s the whole point of rotating the view.','','Their directions are all different after scattering.','They follow genuinely different 3-D trajectories, not scaled copies.'] } },
    { id:'d1d', title:'Parking at the Moon: backwards is better',
      teach:[
        'Suppose you want to <b>leave a satellite near the Moon</b> for years. Around Earth (Modules 1–3) any circular orbit works. Around the Moon it’s not so simple — <b>Earth’s tide is always tugging</b>, and far enough out it can strip a satellite away entirely.',
        'The <b>🔄 DRO vs prograde</b> release parks seven satellites around the Moon: three <b>retrograde</b> (circling the Moon backwards, as seen in the rotating frame) at 30, 40 and 55 thousand km, three <b>prograde</b> twins at the same radii, and one close-in prograde at 20,000 km. The retrograde ones are <b>Distant Retrograde Orbits (DROs)</b> — famously stable; it’s where <b>Artemis I parked the Orion capsule</b> in 2022. The prograde twins are doomed: Earth’s tide pumps them up and strips them off (one even spirals into the Moon). Only close in, where the Moon’s grip is overwhelming, does prograde survive.',
      ],
      predict:'Same radius, same speed — only the direction (prograde vs retrograde) differs. Do you expect that to matter? Which sense survives?',
      do:[
        'Pick <b>🔄 DRO vs prograde</b> and press <b>▶ release</b>. Watch in <b>Moon-centered inertial</b> or the <b>synodic</b> frame.',
        'Speed up with <kbd>.</kbd>. Within days the far prograde satellites distort, swing wide, and are <b>stripped</b> — the “stripped from the Moon” counter tracks them (one is flung 2.3 million km; the 30k prograde one craters into the Moon around day 39).',
        'Let it run for weeks: every <b>retrograde</b> orbit just keeps looping, only gently flexed by the tide. So does the close-in 20k prograde one.',
      ],
      observe:'direction is destiny: at the same radii, retrograde (DRO) orbits persist for months while prograde ones are stripped away or crash — and close in, both survive.',
      think:[
        'Same radius, same speed, opposite direction — why does retrograde resist the tide so much better? (Think about how fast the satellite sweeps past the Earth–Moon line in the rotating frame.)',
        'Why did NASA choose a DRO to park Orion during Artemis I?',
        'The 20,000-km prograde orbit survived. What does that tell you about WHERE the Earth’s tide matters?',
      ],
      quiz:{ q:'Two satellites orbit the Moon at 40,000 km — identical except one is prograde, one retrograde (a DRO). What happens over the following weeks?',
        opts:['Both are equally stable — direction can’t matter',
              'The prograde one is stripped away by Earth’s tide within days; the retrograde (DRO) one persists — which is why Artemis I parked Orion in a DRO',
              'The retrograde one crashes immediately — orbiting backwards is unstable','Both are stripped away; nothing can orbit the Moon that far out'],
        a:1, why:'Correct — at large radii Earth’s tide destroys prograde lunar orbits but leaves distant retrograde orbits stable for months to years, which is exactly why DROs are used for parking real spacecraft.',
        feedback:['Direction matters enormously out here — that’s the whole demo.','','Backwards (retrograde, in the rotating frame) is the STABLE sense at these radii.','Retrograde orbits DO survive that far out — that’s what makes DROs useful.'] } },
    { id:'d1e', title:'The free-return figure-8 — 6 m/s from home',
      teach:[
        'One more release, and it’s the most famous trajectory in spaceflight. A <b>free-return</b> path leaves Earth, loops around the <b>far side of the Moon</b>, and falls home to re-entry — <b>with no burn at the Moon</b>. Gravity does everything after departure. Apollo rode free-returns because they’re fail-safe: if the engine dies (Apollo 13!), you still come home.',
        'The <b>∞ free return</b> release sends seven ships off a 330-km parking orbit with departure speeds spanning just <b>~6 m/s in total</b> — the pace of a brisk walk, on top of 10,800 m/s. That whisker is the whole difference between re-entering at home, missing Earth by 80,000 km, being stranded near lunar distance, or hitting the Moon.',
      ],
      predict:'Seven ships, departure speeds within 6 m/s of each other. How different can their fates be?',
      do:[
        'Pick <b>∞ free return</b> and press <b>▶ release</b>. Watch in the <b>Earth-centered inertial</b> frame to see the figure-8 shape.',
        'Follow them out (~5 days to the Moon). <b>Green</b> and <b>cyan</b> thread the figure-8 and <b>re-enter around day 8</b> — a green splashdown banner marks the first one home. Keep watching: <b>pale</b> straggles home around day 13 and <b>pink</b> around day 18 — <b>4 of 7 eventually make it back</b>, but only the true free-returns arrive on a schedule a crew could survive on.',
        'Track the failures: <b>red</b> cuts inside one lunar radius and craters (~day 5); <b>yellow</b> and <b>purple</b> are slung wide and still haven’t come home after <i>months</i>. The “came home so far” counter keeps score.',
      ],
      observe:'a ~6 m/s spread at departure fans out into on-time re-entry, days-late re-entry, months of stranding, and a lunar impact — and the ships that do come home used no propellant at all after leaving Earth.',
      think:[
        'Why is a free-return trajectory the safest way to send people to the Moon?',
        'The speed differences are ~0.05% of the departure speed. Why does the Moon amplify them so violently? (Which earlier release does this echo?)',
        'Apollo 13’s explosion happened on the way out. Why did the crew survive?',
      ],
      quiz:{ q:'What makes a free-return trajectory special — and why did Apollo use one?',
        opts:['It’s the fastest possible route to the Moon',
              'After the departure burn, gravity alone loops the ship around the Moon’s far side and brings it home to re-entry — no burn needed at the Moon, so an engine failure isn’t fatal',
              'It uses the Moon to fling the ship out of the Earth–Moon system','It requires continuous thrusting to hold the figure-8 shape'],
        a:1, why:'Correct — the figure-8 free return is fail-safe: Earth, Moon, and geometry do all the work after departure, which is exactly what saved Apollo 13.',
        feedback:['It’s about safety, not speed.','','That’s the scatter release — a free return comes HOME.','No thrust at all after departure — that’s the whole point.'] } },
    { id:'d1m', title:'Earth’s temporary minimoons',
      teach:[
        'Earth occasionally has <b>more than one moon</b>. Small asteroids drifting past can be <b>ballistically captured</b>: a well-timed lunar flyby steals enough of their energy to leave them gravitationally bound to Earth — a <b>minimoon</b> — until a later encounter hands the energy back and releases them. This really happens: asteroid <b>2006 RH120</b> orbited Earth for about 11 months in 2006–07, and <b>2020 CD3</b> stayed for roughly two years. No engines, no burns — pure gravity.',
        'The <b>🌒 minimoons</b> release sends seven objects sunward-in from a million km out. Every one is slightly <b>hyperbolic</b> — NOT bound to Earth — with identical speed and identical aim. The only thing that differs is <b>which day each arrives</b>, which changes where the Moon happens to be. Watch the “captured right now” counter: it tracks how many currently have negative orbital energy — i.e., how many moons Earth has at the moment.',
      ],
      predict:'Seven identical unbound arrivals, differing only in arrival day. Can gravity alone make any of them orbit Earth? For how long?',
      do:[
        'Pick <b>🌒 minimoons</b> and press <b>▶ release</b>. Watch in the <b>Earth-centered inertial</b> frame, zoomed well out.',
        'A green banner marks the first <b>ballistic capture</b>. Watch the counter rise and fall as objects are caught and released.',
        'Be patient: the infall takes ~3 weeks of sim time (~25 s at the default speed) before anything can be captured — a <b>green halo ring</b> lights around each object while it is bound to Earth. Follow individual fates: <b>yellow</b> and <b>pink</b> stay captured for over a <i>year</i> of sim time; <b>green</b> and <b>purple</b> are minimoons for ~3 weeks; <b>cyan</b> sails straight through; <b>red</b> arrives at exactly the wrong moment and hits the Moon.',
        'Note how irregular the captured orbits look — huge, lopsided, never repeating. Real minimoons are like this, which is one reason they’re hard to spot.',
      ],
      observe:'objects that arrived unbound end up looping Earth for weeks to over a year — captured and eventually released by nothing but lunar flybys — while identical twins arriving on other days pass straight through.',
      think:[
        'Where did a captured object’s excess energy go? (Something else must have gained it.)',
        'All seven were identical except arrival day. What does that tell you about predicting whether a passing asteroid will be captured?',
        'Why are real minimoons so hard to discover? (Think size, brightness, and their weird orbits.)',
      ],
      quiz:{ q:'How does a passing asteroid become a temporary “minimoon” of Earth, with no propulsion involved?',
        opts:['It slows down from friction with the interplanetary medium',
              'A well-timed lunar flyby transfers some of its orbital energy to the Moon, dropping it below escape energy — bound until a later encounter releases it',
              'Earth’s magnetic field captures it','It can’t happen — capture always requires a rocket burn'],
        a:1, why:'Correct — ballistic capture is a gravity-assist in reverse: the flyby geometry hands energy to the Moon, leaving the asteroid temporarily bound. 2006 RH120 and 2020 CD3 were both caught (and later released) exactly this way.',
        feedback:['Space is far too empty for friction to matter here.','','Gravity, not magnetism, does the capturing.','It happens naturally — Earth has had several documented temporary moons.'] } },
    { id:'d2', title:'Why cislunar tracking is hard',
      teach:[
        'Put the pieces together. In simple Earth orbit, a handful of numbers (the elements from Module 3) predict where something will be far into the future. In the tangled, chaotic cislunar field, that breaks down: a small uncertainty in where an object <b>is now</b> becomes a <b>huge</b> uncertainty in where it will be later — exactly the fan-release behavior.',
        'That’s why keeping <b>custody</b> of objects in cislunar space (a theme from Module 4) is so demanding: you must observe them <b>often</b>, because predictions go stale fast. It’s a frontier problem for space domain awareness, and it’s the practical payoff of this whole module.',
      ],
      predict:'Given what the fan release showed, do you expect it to be easier or harder to predict a cislunar object’s future position than a simple Earth-orbiting satellite’s — and why?',
      do:'Reflect on the fan release you just ran. Imagine each dot is a real object you’re trying to track, and you only get to measure its position occasionally.',
      observe:'because paths diverge so fast, a position measured today tells you less and less about tomorrow — you have to keep re-observing.',
      think:[
        'How does chaos turn a small “where is it now?” error into a big “where will it be?” error?',
        'Why does that force you to observe cislunar objects more often than Earth-orbit satellites?',
        'How does this connect to “custody” from Module 4?',
      ],
      quiz:{ q:'Why is predicting a cislunar object’s future position so much harder than for a simple Earth-orbiting satellite?',
        opts:['Cislunar space has no gravity to model','The chaotic Earth+Moon field amplifies tiny “where is it now” errors into huge future errors, so predictions go stale fast and you must re-observe often',
              'Cislunar objects move faster than light','There is no way to observe them at all'],
        a:1, why:'Correct — chaos means small present-day uncertainties explode into large future ones, so cislunar tracking demands frequent re-observation to keep custody.',
        feedback:['There’s plenty of gravity — it’s the complex, chaotic field that’s the problem.','','Nothing moves near light speed; the issue is sensitivity to initial conditions.','They can be observed — just not predicted far ahead without frequent updates.'] } },

    // ---- PART E · capstone: the libration zoo ----
    { id:'e1', title:'How to orbit around nothing',
      teach:[
        'One last, mind-bending idea to end on. Every orbit you’ve met until now goes <b>around a body</b> — a satellite around Earth, the Moon around Earth, a probe around the Moon. A <b>halo orbit goes around nothing at all.</b> It circles a <b>Lagrange point</b> — an empty spot in space with no mass in it. There is no body at the focus because there is <b>no focus</b>: the spacecraft is simply balanced in the combined pull of Earth and Moon, tracing a loop around a point where, if it stopped, it would feel almost no net force. (The showcase NRHO you just watched visibly wraps the Moon — no contradiction: the family shades continuously from Moon-hugging NRHOs at one end to halos looping a truly empty point at the other.)',
        'That means these are <b>not Keplerian orbits</b>. Kepler’s ellipses — and the whole six-element / <b>TLE</b> description from Module 3 — assume one dominant central body. Here there are two, and the field is time-changing, so <b>none of that machinery applies</b>: no semi-major axis, no eccentricity, no fixed ellipse, no TLE. Astonishingly, the entire family of halos around a Lagrange point needs just <b>one number</b> to pin it down — the <b>energy</b> (the Jacobi constant). Set that single knob and the size, the shape, how far it climbs out of the plane, and the period are <b>all determined</b>. One number, versus the six-plus of a normal orbit. (The tool — a simplified, linearized model, as its own panel admits — hands you <b>two amplitude sliders and a frequency ratio</b> instead; but pick a whole-number ratio like the halo’s 1:1 and it 🔒 locks the two sliders together, leaving exactly one free knob: the one-parameter family in disguise.)',
        'And notice something as it circles: in the rotating frame the loop holds a fixed orientation, so in the real (inertial) sky its tilt <b>swings around once a month</b>, keeping pace with the Earth–Moon line. That turning takes a real <b>torque</b> — supplied by the <b>Moon’s off-axis gravity</b> (the Moon doesn’t pull straight through Earth, so its tug twists the orbit around). Same idea as the bead on the rotating rod: real gravity, doing the turning.',
      ],
      predict:'A halo orbit circles a Lagrange point — a spot with no object in it. Before you explore: how many numbers do you think it takes to describe the whole family of these orbits — the usual six orbital elements, or something very different?',
      do:[
        'Open the <b>🌀 Libration zoo — the L1 orbit family</b> scenario. Drag the <b>↔ in-plane amplitude (A<sub>x</sub>)</b> slider and watch the loop grow smoothly — and notice the 🔒 note: on a whole-number ratio the two sliders are <b>locked together</b>, so dragging either walks you along a one-parameter family. That linked pair <i>is</i> the single knob in disguise.',
        'Make sure the frequency ratio is on <b>1:1 (halo)</b> and raise the <b>↕ out-of-plane (A<sub>z</sub>)</b> slider: the in-plane and out-of-plane rhythms match, so the path closes into a clean, tilted 3-D halo that climbs far out of the plane. <b>Rotate with the arrow keys</b> to see the 3-D shape.',
        'Now click <b>irrational</b> with the <b>long trail</b> checkbox on: the two rhythms never line up, so the loop <b>never closes</b> — it endlessly fills a 3-D band. Confirm the orbit is <b>not centered on any body</b>; it wraps the empty ▲ L1 point (use the <b>▲ Lagrange points</b> overlay checkbox to see the point it circles).',
        'Watch one full lap in the <b>ECI</b> frame, then the <b>synodic</b> frame: the loop holds still against the Earth–Moon line but sweeps around once a month against the stars — the precession the Moon’s torque produces.',
      ],
      observe:'the whole family sweeps out from the locked amplitude sliders — at a whole-number ratio one setting fixes everything, echoing the true one-parameter (energy) family; the orbit circles an empty point (no body at the center), never closes unless the two rhythms lock, and its orientation turns once a month in the inertial sky.',
      think:[
        'Why can’t a TLE (the six-element set from Module 3) describe a halo orbit? What assumption behind Kepler’s ellipse breaks here?',
        'A normal orbit needs six-plus numbers; this family needs one. What happened to the other degrees of freedom? (Hint: the rotating two-body field fixes the orientation and links size to shape.)',
        'The loop’s orientation turns once a month in the inertial frame, so its angular momentum changes — what supplies the torque? (Careful: it is real gravity, not the rotating frame.)',
        'In what sense is “orbiting nothing” still just Newtonian gravity — no new physics, only two pulls instead of one?',
      ],
      quiz:{ q:'What is fundamentally different about a halo orbit compared with an ordinary satellite orbit?',
        opts:['It uses a special kind of gravity not found near Earth',
              'It circles an empty Lagrange point (no body at the center), so it is non-Keplerian — no TLE applies — and the whole family is set by a single parameter, the energy',
              'It is a normal ellipse, just drawn in a rotating frame',
              'It needs more orbital elements than a normal orbit, not fewer'],
        a:1, why:'Correct — a halo loops around an empty balance point in the combined Earth+Moon field: not a Kepler ellipse, no focus, no TLE, and the entire family is parameterized by one number (the Jacobi constant / energy).',
        feedback:['It’s ordinary Newtonian gravity — just two bodies pulling at once, not one.','','It is genuinely not an ellipse — there is no single central body and no focus.','It needs FEWER: one parameter sets the whole family, versus six-plus for a Keplerian orbit.'] } },
  ],

  exam: [
    { q:'What is a Lagrange point?',
      opts:['A place with no gravity',
            'A spot where Earth and Moon together give an object the same 27.3-day period as the Moon, so it holds station on the rotating Earth–Moon line',
            'The point where a rocket runs out of fuel',
            'The center of the Moon'],
      a:1, why:'Correct — the five Lagrange points share the Moon’s orbital period, so they stay fixed relative to the Earth–Moon line.',
      feedback:['Gravity is strong there; it’s balanced to a specific period, not zero.','','It has nothing to do with fuel.','It’s a point in space, not inside a body.'] },
    { q:'At L1 the Moon’s pull opposes Earth’s; at L2 the two pulls add. Yet both points share the 27.3-day lunar period. Why does that work?',
      opts:['It doesn’t — the periods are actually different',
            'A closer-in point (L1) needs a gentler pull to take a full month, so opposing pulls help; a farther-out point (L2) needs a stronger pull, so adding pulls help',
            'The Moon has no effect at either point',
            'Both points are the same distance from Earth'],
      a:1, why:'Correct — the Moon adjusts the net pull in exactly the direction each distance needs to match a monthly orbit.',
      feedback:['They genuinely share the Moon’s period — that’s the definition.','','The Moon’s pull is essential at both.','L1 (~326,000 km) and L2 (~449,000 km) are at very different distances.'] },
    { q:'Which statement about stability is correct?',
      opts:['All five Lagrange points are stable','L1 and L2 are stable; L4 and L5 are unstable',
            'L4 and L5 are stable; L1, L2, and L3 are unstable (a golf ball on a basketball)','None of them are stable'],
      a:2, why:'Correct — only L4/L5 are stable; the collinear points L1/L2/L3 are unstable, so missions there fly halo orbits and nudge to stay.',
      feedback:['Only L4/L5 are stable.','It’s the reverse.','','L4/L5 are genuinely stable — debris can gather there.'] },
    { q:'L3 sits on the far side of Earth, directly opposite the Moon. Is it at a smaller or larger orbital radius than the Moon?',
      opts:['Exactly the same radius as the Moon',
            'A slightly LARGER radius — it lies a bit outside the Moon’s orbit',
            'A much smaller radius, down near Earth',
            'Its radius keeps changing, so there’s no answer'],
      a:1, why:'Correct — measured from the barycenter (the point Earth and Moon both circle), L3 sits about 6,600 km OUTSIDE the Moon’s orbital radius. The Moon’s small extra pull, plus the fact that Earth itself circles the barycenter, means L3 must sit a touch farther out to keep the 27.3-day period. The diagram shows it just past the Moon’s ring on the opposite side.',
      feedback:['Close, but not exact — the Moon’s pull and Earth’s own circling shift it outward.','','L3 is far out, opposite the Moon — not near Earth.','It holds a fixed radius; it shares the Moon’s steady period.'] },
    { q:'A near-rectilinear halo orbit (NRHO) skims a few thousand km over one lunar pole and swings ~70,000 km out over the other. Where does the spacecraft spend MOST of its time?',
      opts:['Right over the pole, close to the Moon — that’s the point of the orbit',
            'Far out at the distant end — it whips through the close pass in hours but lingers for days at the far end',
            'Exactly half its time near and half far — the orbit is symmetric in time',
            'It moves at constant speed, so time is spread evenly around the loop'],
      a:1, why:'Correct — like Molniya, an eccentric orbit moves fastest at its closest point and slowest at its farthest, so an NRHO races through the pole pass in hours and dwells far from the Moon for most of each ~6.5-day loop. A “lunar” orbit that’s mostly far from the Moon — counterintuitive but true.',
      feedback:['It only skims the pole briefly — that close pass is the fastest part of the orbit.','','The orbit is very lopsided, so the time split is nowhere near 50/50.','Kepler’s 2nd law: it speeds up when close and slows when far — speed is not constant.'] },
    { q:'The NRHO in the tool is clearly lopsided about the Moon’s orbital plane — close on one side, far on the other. Is that a mistake, given that the Earth+Moon gravity field is mirror-symmetric top-to-bottom?',
      opts:['Yes — a symmetric field must give a symmetric orbit, so the render is wrong',
            'No — the symmetric field allows a matched PAIR of orbits (a northern and a southern halo); each individual orbit is one-sided, and the pair together respects the symmetry',
            'No — the field is actually not symmetric top-to-bottom',
            'Yes — real halo orbits are perfectly symmetric about the orbital plane'],
      a:1, why:'Correct — a symmetric field produces mirror-image northern/southern families; a single halo picks a side (like a ball settling into one well of a symmetric double-well). Gateway flies a southern NRHO; its northern twin is equally valid. The orbit is still symmetric — about the plane through the Earth–Moon line and the poles, not the orbital plane.',
      feedback:['A symmetric field does not force each orbit to be symmetric — only the family as a whole.','','It genuinely is symmetric top-to-bottom; that’s what creates the north/south pair.','Real halos (CAPSTONE, Gateway) are strongly one-sided — northern or southern.'] },
    { q:'A halo orbit is NOT a Keplerian ellipse. Which statement best captures why, and what it takes to describe one?',
      opts:['It is a normal ellipse; a TLE (six elements) describes it just fine',
            'It circles an empty Lagrange point in the combined Earth+Moon field — no single central body, no focus, so no TLE applies — and the whole family is set by ONE number, the energy (Jacobi constant)',
            'It obeys Kepler’s laws but around the Moon instead of the Earth',
            'It needs more than six elements because two bodies pull on it'],
      a:1, why:'Correct — with two bodies and a time-changing field there is no fixed ellipse and no focus, so the six-element/TLE machinery does not apply; remarkably, a single parameter (the energy) pins the entire family.',
      feedback:['A TLE assumes one dominant central body — that fails here.','','Near L1 neither body dominates; it is genuinely two-body balancing.','It needs FEWER, not more: one parameter sets the whole family.'] },
    { q:'A halo loop holds a fixed orientation in the rotating frame, so in the inertial sky it swings around once a month — its angular momentum changes. What supplies the torque?',
      opts:['No torque is needed; it’s just a change of viewpoint',
            'The Moon’s off-axis gravity — its pull does not point straight through Earth, so it exerts a real torque about Earth that turns the orbit once a month',
            'A small onboard thruster fires continuously',
            'Earth’s gravity, which is stronger on the near side'],
      a:1, why:'Correct — Earth’s pull is central about Earth (zero torque about Earth), but the Moon sits off to the side, so its gravity gives a genuine off-axis torque that swings the orbit’s angular momentum around to keep pace with the Earth–Moon line.',
      feedback:['The angular momentum genuinely changes in the inertial frame, so a real torque is required.','','No thrust needed — gravity does it.','Earth’s pull is central about Earth and exerts no torque about it; the Moon’s off-axis pull does.'] },
    { q:'In the lunar-scatter release, an object gets “flung away.” What happened to it?',
      opts:['It lost radio contact','A grazing lunar flyby slung it far beyond Earth’s Hill sphere — out where the Sun’s gravity dominates, so in reality it never comes back',
            'It was captured into a stable lunar orbit','It slowed down and fell to Earth'],
      a:1, why:'Correct — a deep lunar flyby is a gravity assist; it hurled the object past the ~1.5-million-km Hill sphere, beyond which the Sun, not Earth, controls its fate.',
      feedback:['“Flung away” is about energy and distance, not communications.','','Capture is the opposite outcome.','It gained speed and left, rather than slowing and falling.'] },
    { q:'Artemis I parked the Orion capsule in a Distant Retrograde Orbit (DRO). Based on the DRO-vs-prograde release, why?',
      opts:['DROs are closer to the Moon, so they need less fuel to reach',
            'At large distances from the Moon, retrograde orbits resist Earth’s tidal pull and stay stable for months, while prograde ones at the same radius are stripped away',
            'Retrograde orbits are faster, so Orion could return sooner','Prograde orbits are forbidden by international law'],
      a:1, why:'Correct — the release showed it directly: prograde at 40–55 thousand km is stripped in days, while every retrograde twin persists. Stability with no station-keeping is exactly what you want for parking a spacecraft.',
      feedback:['DROs are typically FARTHER out — their advantage is stability, not proximity.','','Speed isn’t the point; surviving Earth’s tide is.','It’s physics, not law — prograde orbits out there simply don’t last.'] },
    { q:'A free-return trajectory (Apollo’s figure-8) is prized because…',
      opts:['it reaches the Moon with the least propellant of any route',
            'after the departure burn, gravity alone carries the ship around the Moon and home to re-entry — so a dead engine doesn’t strand the crew',
            'it lets the ship hover over one spot on the Moon','it avoids the Moon’s gravity entirely'],
      a:1, why:'Correct — the free return is fail-safe by design: no burn is required at the Moon to come home, which is what saved the Apollo 13 crew.',
      feedback:['Its virtue is safety, not propellant optimality.','','Hovering is impossible on any ballistic path.','It USES the Moon’s gravity — that’s what bends the path home.'] },
    { q:'TESS stays on its complex orbit for years because it is…',
      opts:['sitting exactly at L1','in a 2:1 resonance with the Moon, so the Moon’s repeated tugs average out instead of building up',
            'beyond all gravity','burning its thrusters continuously'],
      a:1, why:'Correct — the 2:1 timing arranges the Moon’s pulls to cancel over each cycle, keeping the orbit stable with almost no fuel.',
      feedback:['TESS is on a resonant orbit, not at a Lagrange point.','','Gravity is what shapes the resonance.','The resonance is what avoids the need for constant thrusting.'] },
    { q:'You release two nearly-identical objects in cislunar space. What does the fan-release demo show, and why does it matter?',
      opts:['They stay together, so tracking is easy',
            'They diverge quickly (chaos), so small “where is it now” errors explode into big future errors — making cislunar tracking hard',
            'They orbit the Moon forever','They immediately crash'],
      a:1, why:'Correct — chaotic divergence means predictions go stale fast, which is exactly why cislunar custody requires frequent re-observation.',
      feedback:['They diverge — that’s the whole point of the demo.','','They scatter to many fates rather than settling into one orbit.','They don’t crash immediately; they drift apart unpredictably.'] },
  ],
};
