/* Worksheet 3 content: "Naming Orbits & TLEs".
   Same data-driven shape as worksheets 1 & 2, plus two optional fields the
   worksheet renderer understands: `elements` (the illustration-linked definitions
   table, NO symbols) and per-task `body` (extra HTML such as a sample TLE).
   The interactive tool is tut3.html: six element sliders + live ellipse +
   fixed stars + period/apogee/perigee readouts + "TLE of your orbit" panel +
   clickable real orbits (ISS, GPS, GEO, Molniya, Tundra). */
const WORKSHEET = {
  objectives: [
    'Why every orbit can be pinned down by just <b>six numbers</b> — and what each one controls.',
    'The plain-word meaning of <b>size</b>, <b>shape</b>, <b>tilt</b>, <b>swivel</b>, <b>twist</b>, and <b>position</b>, plus <b>perigee</b> and <b>apogee</b>.',
    'Why <b>size alone sets the period</b>, while re-orienting an orbit leaves its period, apogee, and perigee unchanged.',
    'What a <b>Keplerian orbit</b> is — the idealized, unperturbed ellipse behind all six numbers.',
    'How a <b>Two-Line Element set (TLE)</b> packs those numbers into the text format the Space Force publishes for every tracked object.',
    'Why real orbits (<b>ISS</b>, <b>GPS</b>, <b>GEO</b>, <b>Molniya</b>, <b>Tundra</b>) look the way they do — and slowly drift from their ideal values.',
  ],
  tutorial: [
    'You have watched orbits move. Now you need a way to <b>name</b> one precisely — so a colleague in another building, or an antenna on the far side of the planet, can point at the exact same object. Remarkably, it takes only <b>six numbers</b> to do this.',
    { analogy:'Think of the six numbers as a <b>mailing address</b> for an orbit. A street address is a short, fixed list — number, street, city, ZIP — that lets anyone, anywhere, find one exact house. In the same way, these six values are the complete address of a satellite’s path. Change nothing, and everyone points at the same orbit; change the last number only, and you have moved next door on the same street.' },
    { h:'What the six numbers do' },
    'Two of them set the <b>shape</b> of the ellipse (how big, how stretched). Three <b>orient</b> that ellipse in space (its tilt, and which way it faces). The last one says <b>where the satellite is</b> right now. The full breakdown — plain names, meanings, and which slider each one is — is in the table just below, so drag along as you read it.',
    { figure:'<svg viewBox="0 0 320 180" xmlns="http://www.w3.org/2000/svg"><rect width="320" height="180" fill="#f4f8fc"/><ellipse cx="150" cy="90" rx="120" ry="55" fill="none" stroke="#1a4c8b" stroke-width="2"/><circle cx="196" cy="90" r="18" fill="#2b6fb5"/><circle cx="270" cy="90" r="4" fill="#c0392b"/><text x="232" y="78" font-family="sans-serif" font-size="11" fill="#c0392b">perigee</text><text x="16" y="82" font-family="sans-serif" font-size="11" fill="#1a4c8b">apogee</text><text x="176" y="120" font-family="sans-serif" font-size="10" fill="#5a6270">Earth</text></svg>', caption:'A stretched orbit. The closest point to Earth is <b>perigee</b>; the farthest is <b>apogee</b>. A perfect circle is just the special case where the two are equal.' },
    { h:'Keplerian orbit' },
    'A <b>Keplerian orbit</b> is the idealized, perfectly-repeating ellipse a satellite would trace if Earth were a tidy point of gravity and nothing else ever touched it. It is the clean picture those six numbers describe. Real orbits are nudged by many small effects and slowly drift away from it — the topic of the next module.',
    { h:'Two-Line Element set (TLE)' },
    'A <b>TLE</b> is simply those six numbers written into a fixed-column, two-line block of text — the format the U.S. Space Force publishes for every tracked object. It adds a <b>drag term</b> and an <b>epoch</b> (the timestamp the numbers are valid for). In a TLE the size/period shows up as <b>mean motion</b> (orbits per day) and the position as <b>mean anomaly</b> — steady, clock-like stand-ins for the sliders, chosen because they make predicting a future position easy arithmetic.',
  ],

  // The illustration-linked definitions table (no Greek symbols, by request).
  elements: {
    title: 'The six numbers that name any orbit',
    blurb: 'Every one of these is a slider in the orbit tool. Two set the ellipse itself — <b>size</b> (how big) and <b>eccentricity</b> (how round or oval). Three aim it: <b>inclination</b> tilts the plane, <b>RAAN</b> turns that plane against the fixed stars, and <b>argument of perigee</b> rotates the ellipse within the plane. The last says <b>where the satellite is</b> right now. Open the simulator and drag each one as you read its row.',
    rows: [
      { name:'Size <span style="color:#5a6270">(semi-major axis)</span>',
        meaning:'How big the orbit is — the average of its closest and farthest distances. Size <b>alone</b> sets the orbital period.',
        tool:'Slider 1. Bigger → longer period, higher apogee &amp; perigee.' },
      { name:'Shape <span style="color:#5a6270">(eccentricity)</span>',
        meaning:'<b>Eccentricity says how round or how oval the orbit is.</b> 0 = a perfect circle; closer to 1 = a long, thin cigar. It says nothing about how big the orbit is, and nothing about which way it points.',
        tool:'Slider 2. Watch the circle stretch into an ellipse.' },
      { name:'Tilt <span style="color:#5a6270">(inclination, <i>i</i>)</span>',
        meaning:'<b>Inclination is the tilt of the orbit’s PLANE.</b> Measured against the equator: 0° hugs the equator, 90° goes over the poles, and past 90° the orbit runs against Earth’s spin (retrograde). It sets how far north and south the satellite ever travels.',
        tool:'Slider 3. The ring tips away from the blue equatorial plane.' },
      { name:'Swivel <span style="color:#5a6270">(RAAN)</span>',
        meaning:'<b>RAAN orients that tilted plane against the fixed stars.</b> Tilt says how steeply the plane sits; RAAN says which way it faces. Think of spinning a tilted hula-hoop around the vertical axis — the tilt never changes, only the direction it leans. (Formally “right ascension of the ascending node”. The <b>ascending node</b> is where the orbit crosses the equator heading north, and RAAN is the compass bearing of that crossing, measured against the stars rather than the ground.)',
        tool:'Slider 4a. The plane swivels; the background stars stay put so you can see it.' },
      { name:'Twist <span style="color:#5a6270">(argument of perigee, ω)</span>',
        meaning:'<b>Argument of perigee orients the ELLIPSE inside its own plane.</b> RAAN aimed the plane; this aims the ellipse within it — specifically, where the closest point (perigee) sits. This is the one everybody forgets the name of, and the way to remember it is by what it does: swivel = the plane against the stars, twist = the ellipse inside the plane. (“Argument” is just an old word for “angle” — no dispute involved.)',
        tool:'Slider 4b. The whole ellipse rotates inside its plane; the green/red low &amp; high points move.' },
      { name:'Position <span style="color:#5a6270">(true / mean anomaly)</span>',
        meaning:'Where along the ellipse the satellite is at this instant. This is the only one that changes minute to minute.',
        tool:'Slider 5, or tick “auto-move” to watch the satellite fly.' },
    ],
    foot: 'Two more words you’ll hear constantly: <b>perigee</b> = closest approach, <b>apogee</b> = farthest point. And mind the difference between distance <b>from Earth’s center</b> and <b>altitude above the surface</b> — they differ by one Earth radius (~6,371 km). The tool shows both.',
  },

  parts: [
    { title:'PART A · Exercise the six elements', blurb:'Drag one slider at a time and watch the readouts. The goal is to feel which numbers do what.', tasks:['a1','a2','a3','a4'] },
    { title:'PART B · What stays fixed? (invariants)', blurb:'Some elements reshape the orbit; others only turn it in space. This distinction is the heart of the module.', tasks:['b1','b2'] },
    { title:'PART C · Reading a TLE', blurb:'Connect your six sliders to the text format the Space Force actually publishes.', tasks:['c1','c2','c3'] },
    { title:'PART D · Real orbits & why they’re chosen', blurb:'Load real satellites and discover why their orbits look the way they do.', tasks:['d1','d2','d3','d4'] },
  ],

  summary: [
    'A <b>Keplerian orbit</b> is the idealized, unperturbed ellipse — what you’d get with a perfect point-mass Earth and nothing else acting on the satellite.',
    'It takes <b>six numbers</b>: <b>size</b> &amp; <b>shape</b> set the ellipse; <b>tilt</b>, <b>swivel</b>, and <b>twist</b> orient it in space; <b>position</b> says where the satellite is now.',
    '<b>Size alone sets the period.</b> Turning the orbit (swivel = RAAN, twist = argument of perigee) does <i>not</i> change period, apogee, or perigee — those are invariant under re-orientation.',
    '<b>Perigee</b> = closest, <b>apogee</b> = farthest. Distance <b>from Earth’s center</b> and <b>altitude above the surface</b> differ by one Earth radius (~6,371 km).',
    'A <b>TLE (two-line element set)</b> is just those six numbers written in a fixed-column text format, plus a drag term and an epoch (the timestamp the elements are valid for).',
    'In a TLE, <b>mean motion</b> (orbits per day) encodes the size/period, and <b>mean anomaly</b> is the time-averaged position — both are stand-ins for the sliders you dragged.',
    '<b>Molniya orbits</b> (highly eccentric, ~12-hour, 63.4° inclination, perigee in the south) let a satellite <i>loiter over high northern latitudes</i> for hours — coverage a GEO satellite over the equator can’t give. <b>Tundra</b> is the 24-hour cousin.',
    'The <b>63.4° “magic” inclination</b> freezes the argument of perigee, so apogee stays parked over the same hemisphere instead of drifting.',
    'An orbit is set by Earth’s <b>mass/gravity</b> and the satellite’s velocity in the fixed-star frame — <b>not</b> by Earth’s spin. If Earth stopped rotating, the orbits wouldn’t change (only our ground-relative view of them would).',
    'A TLE describes the <b>ideal (Keplerian)</b> orbit at one epoch. Real orbits drift off it because of perturbations — the subject of the next module.',
  ],

  resources: [
    { t:'Two-line element set (TLE) — Wikipedia', u:'https://en.wikipedia.org/wiki/Two-line_element_set' },
    { t:'Orbital elements — Wikipedia', u:'https://en.wikipedia.org/wiki/Orbital_elements' },
    { t:'Molniya orbit — Wikipedia', u:'https://en.wikipedia.org/wiki/Molniya_orbit' },
    { t:'Tundra orbit — Wikipedia', u:'https://en.wikipedia.org/wiki/Tundra_orbit' },
    { t:'CelesTrak — live TLEs for tracked satellites', u:'https://celestrak.org/NORAD/elements/' },
    { t:'Space-Track.org — the official U.S. catalog', u:'https://www.space-track.org/' },
  ],

  tasks: [
    // ---- PART A: exercise the elements ----
    { id:'a1', title:'Size sets the period',
      teach:[
        'You’ve met the six numbers in the table above; now you get to <i>drive</i> them, one at a time, and watch what each one actually does. Start with the most fundamental: <b>size</b> (its formal name is the <b>semi-major axis</b>, which just means half the long way across the ellipse — the orbit’s average distance from Earth).',
        'Here’s the surprising part worth burning into memory: <b>size alone sets the period</b>. How long a satellite takes to go around depends on nothing but how big its orbit is — not how stretched it is, not how it’s tilted, not where the satellite happens to be right now. Make the orbit bigger and every lap takes longer, exactly the “farther out = slower” pattern you saw in earlier modules, now with a single knob to prove it.',
      ],
      predict:'Before you drag the slider: if you make the orbit bigger, do you think each lap will take more time or less — and do you expect the low point (perigee) and high point (apogee) to move together or in opposite directions?',
      do:'Reset the tool. Drag only the <b>size (semi-major axis)</b> slider from small to large and watch the <b>period</b> readout climb. Then drag it back down and watch the period shrink — sweep it back and forth a couple of times until the link between size and period feels automatic.',
      observe:'a bigger orbit has a longer period, and both apogee and perigee climb together. Size is the one knob that changes how long an orbit takes.',
      think:[
        'As you grow the orbit, do apogee and perigee rise together, or does one move while the other stays put?',
        'You changed nothing but size — yet the period moved every time. What does that tell you about what controls timing?',
        'Roughly how much bigger do you have to make the orbit before the period noticeably doubles?',
      ],
      quiz:{ q:'Which single element determines the orbital period?',
        opts:['Inclination','Size (semi-major axis)','RAAN','Argument of perigee'],
        a:1, why:'Correct — period depends only on the semi-major axis (the orbit’s size). Nothing else changes it.',
        feedback:['Tilt changes orientation, not timing.','','Swivel turns the plane; the period is unchanged.','Twist rotates the ellipse in place; period is unchanged.'] } },
    { id:'a2', title:'Shape: circle to cigar',
      teach:[
        'The second shape number is <b>shape</b> — formally <b>eccentricity</b> — and it measures how <i>stretched</i> the ellipse is. A value of 0 is a perfect circle. Push it toward 1 and the circle pulls out into a longer and longer oval, until at the extreme it’s a thin cigar with Earth tucked way off to one end.',
        'The trick to notice is what happens to the two ends of that cigar. As you stretch the orbit, the <b>perigee</b> (closest point) sinks toward Earth while the <b>apogee</b> (farthest point) balloons outward. They move in <i>opposite</i> directions — yet their average, the size, hasn’t changed. And because the period rides on that average alone, stretching the orbit doesn’t change how long a lap takes. That’s a genuinely counterintuitive fact, and the slider lets you watch it happen.',
      ],
      predict:'Before you drag it: as you stretch a circle into a long ellipse while keeping its size fixed, what do you think happens to the period — does it get longer, shorter, or hold steady?',
      do:'Set <b>size</b> to about 25,000 km or higher, then drag <b>shape (eccentricity)</b> from 0 up toward 0.7. Watch apogee and perigee split apart. (If you started smaller, the tool flashes “⚠ perigee is below the surface” — the low end of your stretched ellipse dips into the Earth. That’s the tool being honest, not broken: give it more size or less stretch.) Now keep your eye on the <b>period</b> readout and drag shape back and forth — confirm for yourself that it doesn’t budge.',
      observe:'the circle stretches into an ellipse: perigee drops closer to Earth while apogee balloons outward — but the period doesn’t change, because the size (average) is fixed.',
      think:[
        'As you crank eccentricity up, which way does perigee move, and which way does apogee move?',
        'Size and period both stayed put while the shape changed wildly — why would the average distance be what timing depends on?',
        'At high eccentricity, how lopsided does Earth’s position inside the ellipse become?',
      ],
      quiz:{ q:'As you increase eccentricity while holding size fixed, what happens?',
        opts:['The orbit stays circular, since only size can change the shape','Perigee drops and apogee rises, but the period does not change','The period gets shorter as the orbit becomes more stretched out','The satellite escapes Earth once eccentricity passes about 0.5'],
        a:1, why:'Correct — eccentricity splits the low and high points apart. Period stays put because it depends on size, not shape.',
        feedback:['Only e = 0 is circular; you’re stretching it.','','Period depends on size, not shape — it’s unchanged.','It stays bound for any e below 1.'] } },
    { id:'a3', title:'Aiming the ellipse: one angle at a time',
      teach:[
        'Size and shape build the ellipse; the remaining numbers <b>aim</b> it in space and place the satellite on it — without changing the ellipse itself at all. The cleanest way to keep them straight is to build the picture <b>one angle at a time</b>, in this exact order, watching what each one does before touching the next. Do this with a <b>strongly elliptical</b> orbit, because on a circle you literally cannot see two of these angles doing anything.',
        '<b>1 · Inclination</b> is the angle of the orbit’s plane measured from Earth’s <b>equatorial plane</b> (the faint blue disk in the tool). Zero means the two planes coincide; 90° is a polar orbit standing perpendicular to the equator.',
        '<b>2 · RAAN.</b> Two tilted planes intersect in a <b>line</b> — the tool draws it in gold (the “line of nodes,” through the two points where the orbit pierces the equatorial plane). RAAN says <b>which direction that intersection line points, measured against the fixed stars</b> (from the grey ♈ reference arrow). That’s all it is: it swings the tilted plane around so its intersection with the equator aims at a chosen point among the stars.',
        '<b>3 · Argument of perigee</b> then rotates the orbital ellipse <b>within that plane</b>: the plane doesn’t move at all; the ellipse spins inside it, carrying the low point (green perigee marker) and high point (red apogee marker) around the ring. This is the element people forget exists.',
        '<b>4 · Mean anomaly</b> — which has to be about the <b>worst name anyone could have chosen</b> for such a simple idea — is nothing more than <b>the angular position of the satellite along its orbit at this instant</b>. The first five numbers describe the racetrack; this one says where the car is right now. (The tool’s “position” slider is this quantity, expressed as the true angle; the TLE writes the time-averaged version, and that’s the one saddled with the awful name.)',
      ],
      predict:'Before you sweep them: which of these four angles will move the perigee/apogee markers, which will move the whole plane, and which will move only the satellite dot? Will any of them change the orbit’s size or period?',
      do:[
        'Set up a <b>strongly elliptical orbit</b>: size ~26,000 km, eccentricity ~0.6. Leave the other sliders at zero for a clean start.',
        'Sweep <b>inclination</b> alone: the orbit plane hinges up out of the equatorial disk. Read the angle between the two planes directly off the picture, then park it around 50–60°.',
        'Sweep <b>RAAN</b> alone: watch the gold <b>line of nodes</b> — the intersection of the orbit plane with the equatorial plane — swing around and point at different background stars. The tilt doesn’t change; only where the intersection line aims.',
        'Sweep <b>argument of perigee</b> alone: the plane now holds perfectly still while the ellipse rotates <i>inside</i> it — the green (perigee) and red (apogee) markers travel around the ring.',
        'Finally sweep <b>position (mean anomaly)</b>: nothing about the orbit moves at all — only the white satellite dot slides along the fixed ellipse. Racetrack vs. car.',
      ],
      observe:'four angles, four completely different jobs: inclination sets the plane-to-plane angle, RAAN aims the planes’ intersection line at the stars, argument of perigee spins the ellipse within its plane, and mean anomaly just marks where the satellite is along it right now.',
      think:[
        'Why did the eccentric orbit matter? What would you NOT have been able to see sweeping argument of perigee on a circular orbit?',
        'State in one sentence what RAAN points at, and what it’s measured against.',
        'Which of the four angles would change where a satellite is at this instant without changing its path at all?',
        'Why is “mean anomaly” such a poor name for “where the satellite is along its orbit”? What would you have called it?',
      ],
      quiz:{ q:'Match the job: which element rotates the orbital ellipse WITHIN its own plane (moving perigee around the ring, plane untouched)?',
        opts:['Inclination','RAAN','Argument of perigee','Mean anomaly'],
        a:2, why:'Correct — argument of perigee is the in-plane rotation. Inclination sets the angle between the orbit plane and the equatorial plane; RAAN aims their intersection line against the fixed stars; mean anomaly (the worst-named of the six) is just where the satellite is along the orbit right now.',
        feedback:['Inclination is the angle between the orbit plane and the equatorial plane.','RAAN aims the two planes’ intersection line against the stars — it moves the whole plane, not the ellipse within it.','','Mean anomaly moves only the satellite dot along the fixed ellipse.'] } },

    { id:'a4', title:'Thought experiment: what if Earth stopped spinning?',
      teach:[
        'Here’s a question that quietly reveals whether the six elements have really clicked: if the Earth suddenly quit spinning, what would happen to the satellites already circling it? Most people’s gut says “everything would fall” or “the orbits would slow down” — and both are wrong.',
        'The key is that an orbit is a contest between just two things: <b>Earth’s gravity</b> (set by its mass) and the satellite’s <b>own velocity</b> through space, both measured against the fixed stars. Earth’s spin appears <i>nowhere</i> in that contest. The planet could stop rotating tomorrow and every satellite would keep tracing the exact same ellipse, at the exact same speed, with all six elements untouched. What <i>would</i> change is only our ground-level description of it: a “geostationary” satellite would stop appearing to hover, because the spot on the ground beneath it stopped moving — not because the orbit changed.',
      ],
      predict:'Before you reason it through: picture the ISS and a GEO satellite the instant Earth’s spin freezes. What’s your first-gut prediction — do they fall, drift, slow down, or carry on exactly as before?',
      do:'Notice that the orbit and its elements are all defined against the <b>fixed stars</b>, not against the ground. The tool even lets Earth rotate underneath a completely unchanging orbit — watch the planet turn while the ellipse holds perfectly still. Now imagine Earth’s spin suddenly froze, and predict what each readout would do.',
      observe:'the orbit doesn’t care. What holds a satellite up is Earth’s <b>mass and gravity</b>, which don’t change if the planet stops rotating. The six elements, the period, apogee, and perigee would all be exactly the same.',
      think:[
        'Which two things actually set an orbit — and is Earth’s rotation rate one of them?',
        'A geostationary satellite would stop “hovering” if Earth froze. Did its orbit change, or only the ground beneath it?',
        'Why does the tool measure the orbit against the stars instead of against the turning ground?',
      ],
      quiz:{ q:'If the Earth suddenly stopped rotating on its axis, how would the orbits of satellites already in space change?',
        opts:['They would all fall out of the sky within a few orbits of the stop','They would not change — an orbit needs Earth’s mass and the satellite’s velocity','Only geostationary ones would change, drifting eastward over the ground','Every orbit would slow until its period matched the stopped Earth'],
        a:1, why:'Correct — a satellite’s orbit is set by Earth’s mass (gravity) and the satellite’s own velocity, both measured against the fixed stars. Earth’s rotation is irrelevant to the orbit itself. (What WOULD change is our ground-based description: a “geostationary” satellite would no longer hover over one spot, because the spot beneath it stopped moving — but the satellite keeps circling exactly as before.)',
        feedback:['Gravity is unchanged, so nothing falls — the orbits are held by Earth’s mass, not its spin.','',
                  'The GEO satellite keeps orbiting unchanged; what changes is only the ground beneath it, so it no longer appears to hover. Its actual orbit is untouched.',
                  'Orbital speed is set by gravity and altitude, not by Earth’s rotation rate — it wouldn’t change.'] } },

    // ---- PART B: invariants (the question the user specifically asked for) ----
    { id:'b1', title:'Turning the orbit vs. reshaping it',
      teach:[
        'This is the single most important idea in the whole module, so it gets its own exercise. There are two fundamentally different things you can do to an orbit: you can <b>reshape</b> it (make it bigger or more stretched), or you can <b>re-orient</b> it (turn it to face a different way in space). The two are completely separate — and the swivel and twist angles do <i>only</i> the second.',
        'When you turn an orbit — swivel its plane, or twist the ellipse within that plane — you are just aiming the same ellipse in a new direction. Its size hasn’t changed, its stretch hasn’t changed, so the <b>period, apogee, and perigee cannot change either</b>. Physicists call quantities that hold steady under a change like this <b>invariants</b>. Proving it to yourself with the readouts is far more convincing than being told.',
      ],
      predict:'Before you move anything: you’re about to swivel and twist the orbit all the way around. Predict which of the three readouts — period, apogee, perigee — will move, and which will sit perfectly still.',
      do:'Watch the period / apogee / perigee readouts. Now change <b>RAAN</b> and <b>argument of perigee</b> across their full range, one and then the other. Iterate: park RAAN at a few different values and, at each, swing the argument of perigee — confirm the three readouts never twitch no matter how you combine them.',
      observe:'the ellipse rotates and swivels in space, but the period, apogee, and perigee numbers do not budge. Re-orienting an orbit doesn’t change its size or shape.',
      think:[
        'You turned the orbit every which way — did any of the three readouts move, even slightly?',
        'What’s the real difference between “reshaping” an orbit and “re-orienting” it?',
        'Why must the period stay fixed if neither the size nor the shape of the ellipse changed?',
      ],
      quiz:{ q:'You change RAAN and argument of perigee through their whole range. Which readouts stay fixed?',
        opts:['None of them — turning the orbit changes every readout on the panel','Period, apogee and perigee all stay exactly where they were','Only the period holds still; apogee and perigee both move','Only apogee holds still, while perigee and period both shift'],
        a:1, why:'Exactly — RAAN and argument of perigee only re-orient the orbit. Period, apogee, and perigee are invariant under them; they’re set by size and shape alone.',
        feedback:['Watch the readouts — they don’t move as you swivel/twist.','','Apogee and perigee are also unchanged — they depend on size and shape.','Period and perigee are unchanged too.'] } },
    { id:'b2', title:'Which elements DO change the readouts?',
      teach:[
        'You just proved that turning an orbit leaves period, apogee, and perigee alone. Now flip the experiment around and find the elements that <i>do</i> move them. If only size and shape carry the ellipse’s dimensions, then only size and shape should be able to shift those three numbers.',
        'This is the tidy payoff of Part A: the six elements split cleanly into two jobs. <b>Size and shape</b> build the ellipse — they own the period, apogee, and perigee. The other four (tilt, swivel, twist, position) only aim it or place the satellite along it, and never touch those readouts. Confirming both halves back-to-back locks the whole picture in place.',
      ],
      predict:'Before you drag anything: you’ve seen the four orientation/position elements leave the readouts frozen. Predict what size and shape will each do to period, apogee, and perigee when you move them.',
      do:'Confirm the flip side: change <b>size</b> and watch all three readouts respond, then change <b>shape</b> and watch apogee and perigee split while the period holds. Iterate between the two sliders until you can predict, before you drag, exactly which of the three numbers will move.',
      observe:'only size and shape move those three numbers. Tilt, swivel, twist, and position leave them alone.',
      think:[
        'Which readouts does size move, and which does shape move — is there any overlap?',
        'Shape splits apogee and perigee apart but leaves the period fixed. Why only those two and not the third?',
        'Can you sort all six elements into “builds the ellipse” versus “aims or places it”?',
      ],
      quiz:{ q:'Which pair of elements actually changes period, apogee, and perigee?',
        opts:['RAAN and inclination, the two angles that aim the orbit plane','Size and shape — semi-major axis and eccentricity','Argument of perigee and position along the orbit','Eccentricity and argument of perigee, taken together'],
        a:1, why:'Correct — size sets the period and the average distance; shape splits that into apogee and perigee. The other four only orient or place the satellite.',
        feedback:['RAAN and inclination only orient the orbit.','','Those place/orient the satellite; they don’t resize the ellipse.','Eccentricity does split apogee and perigee, but its partner here (the twist) only re-orients the ellipse — and neither one touches the period. You need size for that.'] } },

    // ---- PART C: TLEs ----
    { id:'c1', title:'Your orbit as a TLE',
      teach:[
        'Everything you’ve been dragging with sliders, the rest of the world writes down as a <b>TLE</b> — a Two-Line Element set. It’s the plain-text format the U.S. Space Force publishes for every tracked object in orbit, and underneath the cryptic columns it is nothing more than your six numbers, plus a timestamp and a drag term, packed into two fixed-width lines.',
        'Two of the field names look unfamiliar but map straight onto sliders you already know. <b>Mean motion</b> is just the size/period expressed as “orbits per day” — a low, fast orbit racks up ~15 laps a day, while a lazy high one manages about 1. <b>Mean anomaly</b> is just the position element, saying where along the ellipse the satellite sits. Once you can spot those two, a TLE stops being a wall of digits and becomes a readable address.',
      ],
      predict:'Before you look at the panel: if you drag one slider, do you expect only one number in the TLE to change, or several at once? And which field do you think will move when you change the orbit’s size?',
      do:'Look at the <b>“TLE of your orbit”</b> panel. Change a slider and watch the two lines of text update. Match each field to its slider using the map below the TLE. Try it iteratively: drag <b>size</b> and hunt for which number moves, then drag <b>shape</b> and find that one, and so on until you’ve located all six.',
      body:'<p>Here is a real TLE for the International Space Station (the format the Space Force publishes):</p>'+
           '<pre class="tle">ISS (ZARYA)\n'+
           '1 25544U 98067A   24060.51805556  .00016717  00000-0  30777-3 0  9996\n'+
           '2 25544  51.6416 247.4627 0006703 130.5360 325.0288 15.49309239456144</pre>'+
           '<p style="font-size:15px;color:#5a6270">On line 2, in order: <b>51.6416</b> = inclination, <b>247.4627</b> = RAAN, <b>0006703</b> = eccentricity (a leading “0.” is implied → 0.0006703), <b>130.5360</b> = argument of perigee, <b>325.0288</b> = mean anomaly (position), <b>15.4930…</b> = mean motion in orbits per day. Line 1 carries the epoch (when these numbers are valid) and a drag term.</p>',
      observe:'each field in the two lines is one of your sliders in disguise — change a slider and exactly the matching number updates.',
      think:[
        'When you dragged the size slider, which TLE field moved — and does “orbits per day” going up mean a bigger or smaller orbit?',
        'The ISS TLE reads about 15.5 orbits per day. Is that a low, fast orbit or a high, slow one?',
        'Which of the six fields would you expect to be changing constantly for a real satellite, even if nothing else did?',
      ],
      quiz:{ q:'In a TLE, the “mean motion” field is 15.49 orbits per day. What does that tell you?',
        opts:['The orbit is very large (high, slow)','The orbit is low and fast — a LEO satellite','The eccentricity','The inclination'],
        a:1, why:'Correct — ~15.5 orbits per day means a ~93-minute period, i.e. a low, fast LEO orbit like the ISS. Mean motion is just the size/period expressed as revs per day.',
        feedback:['High orbits go slowly — about 1 orbit/day at GEO, not 15.','','Eccentricity has its own field (the “0006703” column) — mean motion encodes the size/period.','Mean motion says nothing about tilt.'] } },
    { id:'c2', title:'Same orbit, two ways of saying position',
      teach:[
        'The tool’s position slider is labeled <b>true anomaly</b> — the honest, geometric angle telling you exactly where on the ellipse the satellite is. But when the TLE prints the position, it uses a different number: <b>mean anomaly</b>. Both point at the same satellite; they’re just two languages for “where is it along the ring.”',
        'Why bother with a second version? Because on a stretched orbit the satellite speeds up near perigee and crawls at apogee, so the true angle races and dawdles unevenly. Mean anomaly is a smoothed, clock-like stand-in that ticks up at a perfectly <b>steady rate</b>. That steadiness is gold for a tracking station: to predict where a satellite will be an hour from now, you just add a fixed amount — simple arithmetic instead of wrestling with the uneven true motion.',
      ],
      predict:'Before you watch it: the auto-move animation advances the satellite the way real time does. On a stretched orbit, do you think the marker will glide around at one steady pace, or race through some parts of the ring and dawdle through others?',
      do:'Crank <b>shape</b> up to ~0.6 so the orbit is clearly stretched, then tick <b>“auto-move the satellite along the orbit”</b> and just watch a few laps (the <b>,</b> and <b>.</b> keys slow it down or speed it up). The marker sprints through perigee and crawls near apogee — Kepler’s 2nd law in real time. As it flies, watch the TLE: the tool’s slider is labeled “true anomaly,” but the TLE prints “mean anomaly.” (If you instead drag the position slider by hand, note that even slider steps are equal <i>angles</i>, not equal <i>times</i> — that’s the uneven true anomaly.)',
      observe:'the auto-move marker advances in mean anomaly — steadily in time — so you can watch the true motion race at perigee and crawl at apogee. Both numbers describe where the satellite is on the ellipse; mean anomaly is the time-averaged version that ground software prefers because it advances at a steady rate.',
      think:[
        'Watching the auto-move on a stretched orbit, where does the satellite spend most of its time — near perigee, or near apogee?',
        'Why would a tracking station prefer a number that ticks up at a steady, predictable rate?',
        'Both numbers describe the same satellite — so what is “mean” anomaly really averaging over?',
      ],
      quiz:{ q:'Why does a TLE list “mean motion” and “mean anomaly” instead of a period and a plain angle?',
        opts:['To obscure the true orbit from anyone reading the published element set','Because those averaged quantities advance at a steady, predictable rate','Because they are simply other names for the satellite’s speed','It is an arbitrary tradition carried over with no technical reason'],
        a:1, why:'Correct — the “mean” quantities change linearly with time, so predicting a future position is simple arithmetic. That’s exactly what a tracking station needs.',
        feedback:['TLEs are public; nothing is hidden.','','Speed varies around an ellipse; these don’t represent speed.','There’s a real reason — steady, linear time behavior.'] } },

    { id:'c3', title:'Two satellites, same orbit — spot the difference',
      teach:[
        'Put the last two ideas together with a concrete puzzle. Imagine two satellites flying the <b>exact same orbit</b> — the same ring traced through space — but spaced apart, one chasing the other like two beads threaded on a single wire. This is precisely how a satellite formation, or a freshly deployed Starlink “train,” is arranged. What would tell their two TLEs apart?',
        'Walk it through element by element: same ellipse means the same <b>size</b>, same <b>shape</b>, same <b>tilt</b>, same <b>swivel</b>, and same <b>twist</b>. Five of the six numbers are identical. The <i>only</i> thing that can differ is <b>position</b> — the mean anomaly — because each satellite sits at a different point along the shared ring. That single differing field is how operators distinguish satellites flying in company.',
      ],
      predict:'Before you reason it out: two satellites on the identical orbit but at different spots. Predict how many of the six TLE fields will match between them, and which one won’t.',
      do:'Picture two satellites flying the exact same orbit (same ring in space), but spaced apart — one chasing the other, like two beads on the same wire. Compare what their two TLEs would look like, field by field. In the tool, you can move only the <b>position</b> slider to stand in for “the second satellite” and watch which single field changes.',
      observe:'five of the six element fields are identical (same size, shape, tilt, swivel, twist — it’s literally the same ellipse). Only the position field differs.',
      think:[
        'Of the six element fields, how many are forced to match if it’s literally the same ellipse?',
        'Which single field carries the “how far apart are they” information?',
        'How would this let an operator tell one satellite in a Starlink train from the next?',
      ],
      quiz:{ q:'Two satellites share the identical orbit but sit at different points along it. Which TLE field differs between them?',
        opts:['Inclination, which fixes how the plane is tilted against the equator','Mean anomaly — where along the orbit the satellite currently sits','Mean motion, which counts how many orbits it completes per day','Eccentricity, which sets how stretched the shared ellipse is'],
        a:1, why:'Correct — same orbit means identical size, shape, tilt, swivel, and twist, so only the mean anomaly (where each one is along the ring) differs. This is exactly how you tell apart satellites in a formation or a Starlink train.',
        feedback:['Same orbit ⇒ same inclination.','','Same orbit ⇒ same size ⇒ same mean motion (period).','Same orbit ⇒ same shape ⇒ same eccentricity.'] } },

    // ---- PART D: real orbits, incl. the Molniya trial-and-error challenge ----
    { id:'d1', title:'Load real orbits and compare',
      teach:[
        'You’ve built orbits from scratch; now meet the ones that actually fly. The tool has presets for real, working satellites, and loading them side by side shows how the same six numbers get dialed to very different settings for very different jobs. Watch especially how <b>size</b> alone drives the period from a brisk hour and a half up to a full day.',
        'The three to start with are the workhorses of near-Earth space. <b>ISS</b> is a low, nearly circular LEO whipping around in about 92 minutes. <b>GPS</b> sits far higher in a circular half-day orbit — roughly 2 laps a day — high enough that a modest fleet keeps several satellites in view for navigation. <b>GEO</b> is the highest of the three, taking exactly one day, which is what lets it hang over a single longitude. Loading each and reading its period turns the abstract “farther = slower” rule into concrete numbers you can quote.',
      ],
      predict:'Before you load them: rank ISS, GPS, and GEO from fastest to slowest lap in your head. Which do you expect to be nearly circular, and which — if any — stretched?',
      do:'In the tool’s <b>“Load a real orbit”</b> list, click <b>ISS</b>, then <b>GPS</b>, then <b>GEO</b>. Read each one’s period and shape as you go. Then reload them in a different order and check your fast-to-slow ranking held up.',
      observe:'ISS is a low, fast, nearly circular LEO (~92 min); GPS is a circular half-day MEO (~12 h, 2 orbits/day); GEO is equatorial and takes exactly one day, so it hangs over one longitude.',
      think:[
        'As you go from ISS to GPS to GEO, does the period climb the way the “farther = slower” rule predicts?',
        'Are these three orbits round or stretched — and does their shape number back that up?',
        'GEO takes exactly one day. Why is that particular period so useful for a communications satellite?',
      ],
      quiz:{ q:'GPS satellites orbit twice a day in a nearly circular orbit. Compared to GEO, GPS is…',
        opts:['Higher than GEO and correspondingly slower around its orbit','Lower and faster — a bit over half GEO’s altitude, ~12-hour period','At the same altitude as GEO, but in a differently tilted plane','Below the ISS, which is why the constellation needs so many satellites'],
        a:1, why:'Correct — GPS sits around 20,200 km with a ~12-hour period, well below the ~35,800 km GEO belt, so it moves faster.',
        feedback:['GPS is lower than GEO, so it’s faster.','','GEO is nearly twice as high as GPS.','GPS is far above the ISS (~20,000 km vs ~420 km).'] } },
    { id:'d2', title:'Invent the Molniya orbit by trial and error',
      teach:[
        'Time to think like a 1960s Soviet engineer with a hard problem. You need to beam communications to the far north of Russia — but a GEO satellite sits over the equator, and from way up at those latitudes it barely clears the horizon. You can’t move the equator, so instead you invent an orbit that <i>loiters</i> high over the north for hours at a stretch. You’re going to build it here, one element at a time, then check your work against the real thing.',
        'Two ideas do the heavy lifting. First, Kepler’s law that a satellite <b>crawls near apogee</b> and races through perigee — so if you park apogee over the north and stretch the orbit hard, the satellite dawdles up there for most of each lap. Second, a “magic” tilt of <b>63.4°</b> that (as the next exercise explains) keeps apogee from drifting off station. Dial size for a 12-hour period, stretch it, twist perigee to the south so apogee rides north, set that magic tilt — and you’ll have reinvented the <b>Molniya</b> orbit from scratch.',
      ],
      predict:'Before you touch the sliders: to make a satellite linger for hours over the far north, which element do you think matters most — how big the orbit is, how stretched it is, or which way the ellipse is twisted? Jot down your guess, then test it.',
      do:[
        'Reset the sliders to start fresh.',
        'Drag the <b>size</b> slider until the <b>period</b> readout reads about <b>12 hours</b>.',
        'Crank <b>shape (eccentricity)</b> up high (~0.7) and watch apogee balloon while perigee drops.',
        'Set <b>argument of perigee (twist)</b> to <b>270°</b> so perigee sits in the south and apogee swings up over the north.',
        'Set <b>inclination</b> to <b>63.4°</b>.',
        'Jot down (or screenshot) your six slider values and your generated TLE — clicking a preset overwrites all six sliders, so your build is about to vanish. Then click the <b>Molniya</b> preset and compare its numbers against your notes: which element were you farthest off on?',
      ],
      observe:'a 12-hour period needs a semi-major axis of ~26,600 km. With high eccentricity, apogee reaches ~40,000 km over the northern hemisphere while perigee skims low in the south. By Kepler’s 2nd law the satellite crawls near apogee — so it loiters over the north for roughly 8 of its 12 hours.',
      think:[
        'How close did your hand-built orbit come to the real Molniya preset — and which element was hardest to guess?',
        'Why does stretching the orbit (high eccentricity) make the satellite linger so long over apogee?',
        'You put perigee in the south so apogee rides north. What would break if you twisted perigee to the north instead?',
      ],
      quiz:{ q:'Roughly what orbital period did you have to dial in for a Molniya orbit?',
        opts:['About 90 minutes','About 12 hours','About 24 hours','About 3 days'],
        a:1, why:'Correct — a Molniya is a ~12-hour (half-day) orbit, semi-major axis ≈ 26,600 km. That timing puts apogee back over the same region twice a day. (Its 24-hour cousin is the Tundra orbit.)',
        feedback:['90 min is a low LEO like the ISS, far too fast.','','24 hours is the Tundra orbit — Molniya is half that.','Far too long — a 12-hour half-day period is the target.'] } },
    { id:'d3', title:'Why the Soviets loved Molniya (and what Tundra adds)',
      teach:[
        'Now step back and see <i>why</i> the orbit you just built beats a geostationary one for the far north. From high latitudes a GEO satellite sits low on the southern horizon — hills, buildings, and the curve of the Earth all get in the way, and the signal skims through a lot of atmosphere. A Molniya satellite, loitering near its high northern apogee for roughly 8 hours of each 12-hour lap, rides high in the sky where the view is clean. String three Molniyas together, handing off as each drops toward perigee, and you get round-the-clock coverage.',
        'The <b>63.4° inclination</b> you dialed in isn’t arbitrary — it’s a “magic” value that freezes the twist (argument of perigee), so apogee stays parked over the north instead of slowly wandering off to another latitude. The <b>Tundra</b> orbit is the same idea stretched to a <b>24-hour</b> period with gentler eccentricity: it traces a lazy figure-eight ground track and lingers over one region a whole day at a time. Compare the two presets and the family resemblance is obvious.',
      ],
      predict:'Before you read the call-out: why do you think a GEO satellite — perfectly good over the equator — does such a poor job serving the far north? And what do you expect changes when you stretch Molniya’s 12-hour orbit out to Tundra’s 24?',
      do:'With Molniya loaded, read the call-out in the tool and note how long it dwells near apogee. Then click <b>Tundra</b> and compare — watch how the longer period and milder eccentricity reshape the orbit and its dwell time. Flip back and forth between the two presets to fix the difference in mind.',
      observe:'a GEO satellite sits over the equator and barely rises above the horizon as seen from far-northern Russia — poor coverage. A Molniya’s long dwell at high-latitude apogee fixes that; a trio gives 24/7 coverage. Tundra is the 24-hour version with milder eccentricity.',
      think:[
        'Why does a satellite sitting low on the horizon give worse coverage than one high overhead?',
        'What does the 63.4° “magic” inclination buy you that a random tilt wouldn’t?',
        'Going from Molniya (12 h) to Tundra (24 h): what changes about how long the satellite stays over one region each lap?',
      ],
      quiz:{ q:'Why did the USSR use Molniya orbits instead of geostationary ones for northern communications?',
        opts:['Molniya orbits were substantially cheaper to launch into from Russia','A geostationary satellite sits over the equator, too low on a northern horizon','Molniya orbits require no station-keeping fuel over their long lifetime','Geostationary orbits are not physically possible that far north at all'],
        a:1, why:'Correct — from far-northern latitudes a GEO bird barely clears the horizon. A highly eccentric Molniya loiters near apogee high over the north, giving hours of good, high-elevation coverage per pass. The 63.4° inclination keeps apogee parked there.',
        feedback:['Launch cost isn’t the reason — it’s coverage geometry.','','Every orbit needs some station-keeping; that’s not the driver.','GEO satellites are visible from the north, just too low on the horizon to be useful.'] } },
    { id:'d4', title:'Sun-synchronous: the orbit that tells time',
      teach:[
        'One more “designer orbit,” and it flies more real satellites than any other on the preset list. An imaging satellite wants to photograph the same places at the <b>same local solar time</b> every day — same Sun angle, same shadows — so yesterday’s picture compares cleanly with today’s. That requires the <b>orbit plane to keep a fixed angle to the Sun</b> while Earth goes around it: the plane must swivel (precess its RAAN) by <b>+0.9856° every day</b>, exactly matching the Sun’s apparent annual motion.',
        'Nature sells exactly that swivel, free of charge. Earth’s <b>equatorial bulge (J2)</b> — the same effect that pins Molniya’s apogee at 63.4° — torques every orbit plane by an amount that depends on altitude and tilt.',
        'Tip a ~700-km orbit <b>past the pole</b>, to an inclination of <b>i = 98.2°</b>, and the bulge precesses the plane at precisely the Sun’s rate, forever, with no fuel. (<b>i</b> is the symbol for inclination. Past 90° the orbit is <b>retrograde</b> — it travels against Earth’s rotation rather than with it, which is what flips the direction of the precession and makes the whole trick possible.) Ride the day–night <b>terminator</b> and your solar panels never see shadow.',
        'You can set this up yourself: the inclination slider goes all the way to 180°, and the simulator computes the real J2 precession from your numbers — so the ☀ readout locks because the physics locks, not because it was told to.',
      ],
      predict:'The Sun’s direction moves ~1°/day around the sky over a year. What would happen to a normal (say ISS-like) orbit plane’s lighting over a few months? What must an orbit do to keep its lighting constant?',
      do:'Load the <b>Sun-synchronous</b> preset and turn on <b>auto-move</b>. Watch the ☀ readout in the corner: the <b>node−Sun angle holds fixed</b> while the stars wheel past — the plane and the Sun swivel together (the readout flags it “☀-synchronous!”). Speed up with <kbd>.</kbd> to watch weeks pass. Then load the <b>ISS</b> and watch the same readout drift by about <b>−5°/day</b> — its lighting never repeats. Try dragging <b>inclination</b> a few degrees off 98.2° and watch the lock break.',
      observe:'at i = 98.2° and ~700 km, J2 precesses the plane at exactly the Sun’s +0.9856°/day — the node−Sun angle freezes. Any other tilt (or the ISS) drifts out of step within days.',
      think:[
        'Why must the orbit be tilted PAST the pole (retrograde) to get an eastward plane-swivel? (Which way does J2 push a prograde orbit’s node — check the ☀ readout’s sign on the ISS.)',
        'Why is “same local solar time every pass” so valuable for reconnaissance and change detection?',
        'This trick and Molniya’s frozen apogee both come from J2. What does that tell you about “perturbations” — are they always a nuisance?',
      ],
      quiz:{ q:'What makes a sun-synchronous orbit sun-synchronous?',
        opts:['It flies high enough that the Sun is never eclipsed by the Earth','Its ~98° retrograde tilt lets Earth’s bulge precess the plane +0.9856°/day','It completes exactly one orbit per day, holding over one longitude','Its solar panels are steered continuously to keep facing the Sun'],
        a:1, why:'Correct — J2 nodal precession, tuned by altitude and inclination to match the Sun’s annual rate. Constant lighting geometry for free — which is why nearly every imaging satellite flies it.',
        feedback:['Altitude alone doesn’t lock lighting geometry — the plane must precess with the Sun.','','That’s GEO — a completely different (equatorial, high) orbit.','Panel pointing doesn’t change the orbit’s lighting geometry each pass.'] } },
  ],

  exam: [
    { q:'Which single orbital element determines how long one orbit takes (the period)?',
      opts:['Shape (eccentricity)','Tilt (inclination)','Size (semi-major axis)','Swivel (RAAN)'],
      a:2, why:'Right — the period depends only on the orbit’s size; the other five leave the timing alone.',
      feedback:['Shape splits apogee and perigee apart but leaves the period unchanged.','Tilt only orients the plane against the equator.','','Swivel only turns the plane in space; the period is unchanged.'] },
    { q:'You leave size and shape alone but sweep RAAN (swivel) and argument of perigee (twist) through their full range. What stays the same?',
      opts:['The period, apogee and perigee all stay exactly as they were','Nothing stays fixed — sweeping those angles changes every readout','Only the inclination holds still while the other readouts move','Only the position along the orbit stays where it started'],
      a:0, why:'Correct — those two angles merely re-orient the ellipse; its period, apogee, and perigee are set by size and shape alone.',
      feedback:['','Re-orienting an orbit does not resize or reshape it, so those three readouts hold steady.','Inclination is a third orientation angle you did not touch — but the invariants asked about are period, apogee, and perigee.','Position changes with time regardless; the question is about what re-orienting leaves fixed.'] },
    { q:'What is a Two-Line Element set (TLE)?',
      opts:['A live telemetry feed streamed down directly from the satellite','A fixed-column text format holding six numbers, a drag term and an epoch','The upper-stage engine that pushes a satellite into its final orbit','A ranking of the two most operationally important satellites in a set'],
      a:1, why:'Correct — a TLE is just the orbital elements written into a compact, standardized two-line block of text.',
      feedback:['A TLE is plain text, not imagery or video.','','A TLE describes an orbit; it is not hardware.','“Two-line” refers to the two lines of text, not to a top-two list.'] },
    { q:'Two satellites fly the exact same orbit but sit at different points along it. In their TLEs, which field differs?',
      opts:['Inclination, the tilt of the shared orbital plane against the equator','Eccentricity, which sets how stretched the shared ellipse happens to be','Mean anomaly, which says where along the orbit each one currently sits','Mean motion, the number of complete orbits each finishes per day'],
      a:3, why:'Correct — same orbit means identical size, shape, tilt, swivel, and twist, so only the position (mean anomaly) sets them apart.',
      feedback:['Same orbit means the same tilt, so inclination matches.','Same orbit means the same shape, so eccentricity matches.','Same orbit means the same size and period, so mean motion matches.',''] },
    { q:'A "Keplerian orbit" is best described as…',
      opts:['Because the slots along the belt are marked out at that angle','Because Earth’s spin axis is tilted 23.5° away from its orbital plane','Because the satellites are deliberately launched into inclined orbits','Because the Sun’s apparent yearly path is tilted by that same amount'],
      a:1, why:'Correct — it is the clean, perfectly-repeating ellipse the six elements describe, before real-world perturbations nudge it.',
      feedback:['Polar paths are one inclination among many; that is not what “Keplerian” means.','','That describes a geostationary orbit specifically, not the general Keplerian ideal.','Kepler described the mathematics of orbits centuries before any satellite existed.'] },
  ],
};
