/* Worksheet 5 — xGEO / Cislunar Space.
   Learning objective spine: things orbit the Moon too; the Earth–Moon–Sun
   system; the FOUR reference frames (the big idea); defining xGEO; the Hill
   sphere boundary; Moon phases, tidal locking, and the three tilted
   planes; and a first "lead the Moon" transfer. Interactive tool: tut5.html
   (3 zoom scales × 4 frames + lunar orbiters, xGEO objects, Hill sphere,
   release-on-the-line, and a TLI). */
const WORKSHEET = {
  objectives: [
    'why spacecraft orbit the <b>Moon</b> in ellipses too — and why orbiting and escaping the Moon takes far less speed than at Earth',
    'how the <b>tug-of-war</b> between bodies decides which one you orbit — the Moon’s <b>Hill sphere</b> (~61,500 km) and the <b>balance point</b> on the Earth–Moon line',
    'why the <b>balance point</b> (the L1 point) sits about 85% of the way to the Moon instead of at the midpoint',
    'what <b>xGEO</b> (cislunar space) means, and where its inner and outer boundaries lie',
    'how to switch between the <b>four reference frames</b> — and why the right frame turns a confusing tangle of motion into a simple, steady picture',
    'why reaching the Moon means <b>leading it like a duck hunter</b>',
  ],
  tutorial: [
    'Everything so far has orbited Earth. But go far enough and the <b>Moon’s</b> gravity — and eventually the Sun’s — starts to matter. <b>Cislunar space</b> is the whole Earth–Moon–Sun neighborhood. <b>xGEO</b> is the slice of it that lies beyond the crowded GEO belt (~36,000 km) yet is still held by Earth, reaching out to Earth’s gravitational edge at ~1.5 million km. The Moon, at 384,400 km, sits squarely inside it.',
    'One honest refinement before we go on. We keep saying "the Moon orbits the Earth," but strictly, <b>two gravitationally bound bodies both orbit their common center of mass</b> — the <b>barycenter</b> — with the heavier one making the smaller circle. Earth outweighs the Moon about 81:1, so the Earth–Moon barycenter sits only ~<b>4,670 km from Earth’s center</b> — that is <i>inside the planet</i>, about 1,700 km beneath your feet — and Earth swivels around that buried point once a month while the Moon swings its big circle. For the <b>satellites</b> you’ve flown so far the refinement vanishes: a spacecraft’s mass is so utterly negligible next to Earth’s (or the Moon’s) that its barycenter with the parent IS the parent’s center, and "it orbits the center of the Earth" is exact for every practical purpose. The distinction only starts to matter when the two bodies are comparable — like Earth and Moon — and it will pay off later in this module, when a frame centered on that barycenter makes the whole cislunar stage sit still.',
    { h:'The tug-of-war: whose gravity wins?' },
    'Every body owns a patch of space where its pull beats its neighbor’s — its <b>Hill sphere</b>. Inside the Moon’s Hill sphere (~61,500 km radius) you orbit the Moon; outside it, Earth takes over. On the Earth–Moon line there’s a <b>balance point</b> — the spot where the Moon’s gravity, plus the orbital (rotating-frame) effect of the whole system turning, exactly balances Earth’s pull. This is the <b>L1 Lagrange point</b>, and it sits roughly <b>85% of the way to the Moon</b>, not at the midpoint. Release an object at rest on the — rotating — Earth–Moon line, keeping pace with it, closer than that and it falls back to Earth; beyond it, onto the Moon. (For an object truly at rest, with no share of the line’s monthly turning, gravity alone would balance a bit farther out — about 90% of the way.)',
    { figure:'<svg viewBox="0 0 460 132" width="100%" role="img" aria-label="Earth and Moon joined by a line, with the balance point marked at about 85 percent of the way to the Moon"><rect x="0" y="0" width="460" height="132" rx="8" fill="#f4f6f9"/><line x1="74" y1="72" x2="400" y2="72" stroke="#ff5a52" stroke-width="2"/><circle cx="48" cy="72" r="26" fill="#2b6fb5"/><circle cx="410" cy="72" r="10" fill="#d8d2c4" stroke="#b8b2a4" stroke-width="1"/><line x1="356" y1="58" x2="356" y2="86" stroke="#ff5a52" stroke-width="2"/><text x="48" y="118" text-anchor="middle" font-family="sans-serif" font-size="13" fill="#2b6270">Earth</text><text x="410" y="118" text-anchor="middle" font-family="sans-serif" font-size="13" fill="#2b6270">Moon</text><text x="356" y="50" text-anchor="middle" font-family="sans-serif" font-size="12" fill="#c8332c">balance · ~85%</text></svg>', caption:'The Earth–Moon line, with the balance point about 85% of the way to the Moon — far from the midpoint. This is the L1 point, where the Moon’s gravity plus the orbital (rotating-frame) effect balance Earth’s pull; it also roughly coincides with the edge of the Moon’s Hill sphere.' },
    { h:'Reference frames: what do you choose to hold still?' },
    'A <b>reference frame</b> is simply your choice of what to hold still while you watch everything else move. The very same motion can look like a hopeless tangle or a calm, steady picture depending on that one choice — and picking the right frame is the core skill of this whole module. There are <b>four</b> frames worth knowing; the table below lays out exactly what each one centers on and whether it turns with the Earth–Moon line, so we won’t repeat them here.',
    { analogy:'Watch a carousel from the ground and the painted horses gallop around you. Now climb onto a horse: everything flips. The carousel’s center and the other horses suddenly sit perfectly still, while the whole fairground swings past instead. Nothing about the ride changed — only where you chose to stand. That switch is exactly what changing a reference frame does.' },
  ],

  // The four reference frames, as a definitions table (matches the tool's frame buttons).
  elements: {
    title: 'The four reference frames',
    blurb: 'The whole module turns on this table. Each frame is defined by two choices: <b>what it centers on</b>, and <b>whether it turns with the Earth–Moon line</b>. Use the tool’s frame buttons — or the 2×2 compare view — to see each one. Same dynamics every time; only the vantage point changes.',
    rows: [
      { name:'Earth-centred inertial <span style="color:#5a6270">(ECI)</span>',
        meaning:'Centered on Earth, not turning (fixed to the stars). The <b>Moon orbits the Earth</b> once a month; distant stars stay put.',
        tool:'Frame 1. The honest physics frame, and the default for Earth-orbit work.' },
      { name:'Earth–Moon rotating <span style="color:#5a6270">(synodic)</span>',
        meaning:'Centered on Earth, <b>turning once a month with the Earth–Moon line</b>, so the Moon appears <b>frozen</b> in place. The Earth–Moon line and everything tied to it hold still.',
        tool:'Frame 2. The natural frame for studying transfers.' },
      { name:'Moon-centred inertial <span style="color:#5a6270">(MCI)</span>',
        meaning:'Centered on the Moon, not turning. From here the <b>Earth appears to orbit the Moon</b> once a month — the same relative motion, seen from the other body.',
        tool:'Frame 3. Natural for arriving-at-the-Moon problems.' },
      { name:'ECL-EMBR <span style="color:#5a6270">(barycentric rotating)</span>',
        meaning:'Centered on the <b>Earth–Moon barycenter</b> — the shared center of mass both bodies circle — and <b>turning once a month with the line</b>, in the plane of the <b>ecliptic</b>. Here <b>BOTH Earth and Moon sit frozen</b> on the axis. In reality it is <b>Earth that swivels</b> around the barycenter once a month (the point sits ~4,670 km from Earth’s center — actually inside the Earth). This is the frame in which the <b>five Lagrange points hold still</b>, so it is the natural stage for cislunar orbits and the whole of Module 6.',
        tool:'Frame 4. The cislunar / Lagrange frame. The orange cross marks the barycenter (drawn exaggerated for visibility); the sim keeps Earth pinned so you can see everything else, so picture Earth’s monthly wobble about that cross rather than watching for it. Note the tilted equator vs. the ecliptic plane.' },
    ],
    foot: 'Rule of thumb: <b>center on the body (or point) you care about</b>, and <b>co-rotate if you want a moving line or point to hold still</b>. The last frame centers on the <b>barycenter</b> — the deep insight is that Earth and Moon <i>both</i> orbit that shared point, and holding it still is what freezes the Lagrange points you will meet in Module 6.',
  },

  parts: [
    { title:'PART A · Orbiting the Moon', blurb:'Just like Earth, the Moon holds satellites in elliptical orbits.', tasks:['a1','a2'] },
    { title:'PART B · The tug-of-war: Earth vs. Moon vs. Sun', blurb:'How far can you go and still orbit the Moon? Where does Earth hand you off to the Sun?', tasks:['b1','b2','b3'] },
    { title:'PART C · Reference frames — the big idea', blurb:'The same motion, four different ways of looking at it.', tasks:['c1','c2','c3','c4','c5'] },
    { title:'PART D · The Moon itself', blurb:'The Moon is just another Earth satellite — with some special properties.', tasks:['d1','d2','d3'] },
    { title:'PART E · Defining xGEO', blurb:'Putting a boundary on the region this whole course has been building toward.', tasks:['e1'] },
    { title:'PART F · Flying to the Moon', blurb:'Lead the Moon like a duck hunter.', tasks:['f1','f2'] },
  ],

  summary: [
    'The Moon has its own gravity, so spacecraft orbit it in <b>ellipses</b> just like they orbit Earth — low lunar orbit is ~1.63 km/s, and lunar escape is ~2.38 km/s (much less than Earth’s, because the Moon is small).',
    'Which body you orbit is a <b>tug-of-war</b>. The Moon’s gravitational “territory” is its <b>Hill sphere</b>, radius ~61,500 km — roughly where the Moon’s pull stops beating Earth’s along the Earth–Moon line. Inside it you orbit the Moon; outside, the Earth.',
    'The <b>balance point sits ~85% of the way to the Moon</b>, not at the midpoint — this is the <b>L1 Lagrange point</b>, where the Moon’s gravity plus the orbital (rotating-frame) effect balance Earth’s pull. Release an object at rest closer than that and it falls back to Earth; beyond it, onto the Moon.',
    'The same handoff happens one level up: inside the edge of Earth’s <b>Hill sphere</b> (~1.5 million km) you orbit the Earth; beyond it, the Sun takes over.',
    '<b>xGEO</b> (“extended GEO”) is the region <b>beyond the GEO belt (~36,000 km) but inside Earth’s grip (out to the edge of Earth’s Hill sphere, ~1.5 million km)</b>. The Moon, at 384,400 km, sits right in it.',
    'The big skill is choosing a <b>reference frame</b>: <b>Earth-centred inertial (ECI)</b> (fixed to the stars — the Moon orbits Earth); <b>Earth–Moon rotating (synodic)</b> (the Earth–Moon line held fixed — ideal for studying transfers); <b>Moon-centred inertial (MCI)</b> (the same motion seen from the Moon); and <b>ECL-EMBR</b> — centred on the Earth–Moon <b>barycenter</b> and co-rotating in the ecliptic, the frame in which <b>both bodies freeze and the Lagrange points hold still</b> (the stage for Module 6).',
    'The Moon is just another <b>Earth satellite</b>: a slightly elliptical orbit (e≈0.055), inclined ~5° to the ecliptic, period one month.',
    'The Moon is <b>tidally locked</b> — the same face always points at Earth — so it rotates exactly once per orbit. (Why it’s locked is beyond our scope; see the resources.)',
    'Three planes are all tilted relative to each other: Earth’s <b>equatorial plane</b>, the <b>ecliptic</b> (Earth’s orbit around the Sun), and the <b>Moon’s orbital plane</b>. That’s why eclipses are occasional, not monthly.',
    '<b>Moon phases</b> come from the Sun–Earth–Moon geometry over the ~29.5-day cycle — the same illumination idea as a satellite lit by the Sun.',
    'Reaching the Moon means <b>leading it like a duck hunter</b>: you burn into a transfer orbit aimed at where the Moon <i>will be</i> when you arrive at apogee, not where it is now.',
  ],

  resources: [
    { t:'Cislunar space / space (region) — Wikipedia', u:'https://en.wikipedia.org/wiki/Cislunar_space' },
    { t:'Hill sphere — Wikipedia', u:'https://en.wikipedia.org/wiki/Hill_sphere' },
    { t:'Orbit of the Moon — Wikipedia', u:'https://en.wikipedia.org/wiki/Orbit_of_the_Moon' },
    { t:'Tidal locking (why one face) — Wikipedia', u:'https://en.wikipedia.org/wiki/Tidal_locking' },
    { t:'Lunar phase — Wikipedia', u:'https://en.wikipedia.org/wiki/Lunar_phase' },
    { t:'Ecliptic (Earth’s orbital plane) — Wikipedia', u:'https://en.wikipedia.org/wiki/Ecliptic' },
    { t:'Rotating reference frame — Wikipedia', u:'https://en.wikipedia.org/wiki/Rotating_reference_frame' },
    { t:'Trans-lunar injection — Wikipedia', u:'https://en.wikipedia.org/wiki/Trans-lunar_injection' },
    { t:'Lunar Reconnaissance Orbiter (LRO)', u:'https://en.wikipedia.org/wiki/Lunar_Reconnaissance_Orbiter' },
    { t:'CAPSTONE (near-rectilinear halo orbit)', u:'https://en.wikipedia.org/wiki/CAPSTONE_(spacecraft)' },
  ],

  tasks: [
    // ---- PART A: orbiting the Moon ----
    { id:'a1', title:'Spacecraft orbit the Moon too',
      teach:[
        'You spent the last few modules watching things orbit <b>Earth</b>. Here’s the first mental shift of cislunar work: the <b>Moon has its own gravity</b>, so it holds satellites too. Anything with mass pulls on everything near it, and the Moon has plenty — about 1/6 of Earth’s surface gravity. Send a spacecraft close enough and slow enough, and the Moon captures it into orbit exactly the way Earth does.',
        'And the shapes are the same. A spacecraft circling the Moon traces an <b>ellipse</b> — the very same conic-section paths you built by hand back in Module 3, with a circle as the special case. Only the numbers change: the Moon is smaller, so its orbits are gentler and slower. <b>LRO</b>, the Lunar Reconnaissance Orbiter, rides a low, near-polar orbit so it can map the whole surface as the Moon turns beneath it.',
      ],
      predict:'Before you turn on LRO: you learned that Earth satellites move in ellipses. Do you expect a spacecraft orbiting the Moon to trace the same kind of path, or something different because it’s a different world?',
      do:'The tool opens at the Earth–Moon scale; click the <b>Low lunar orbit</b> zoom. Turn on the <b>LRO</b> orbiter and watch it circle the Moon. Then compare it with the <b>Elliptical lunar orbit (apogee ≈ ½ Hill radius)</b>, which is already on — its stretched shape against LRO’s tighter, rounder one.',
      observe:'the Moon has its own gravity, so spacecraft circle it just as they circle Earth — and these are <b>ellipses</b>, the same shapes you learned in Module 3. LRO maps the Moon from a low, near-polar orbit.',
      think:[
        'Does LRO’s path look like any of the orbit shapes you built around Earth in Module 3?',
        'The Moon has no thick atmosphere to fall through — so what is actually holding LRO in its orbit?',
        'How is the elliptical science orbit shaped differently from LRO’s near-circular one?',
      ],
      quiz:{ q:'Spacecraft in orbit around the Moon follow what kind of path?',
        opts:['Perfect circles only','Ellipses — the same conic-section orbits as around Earth, just governed by the Moon’s gravity',
              'Straight lines','They can’t orbit the Moon — it has no gravity'],
        a:1, why:'Correct — any body with mass has gravity, so orbits around the Moon are ellipses (or circles, the special case) exactly like around Earth. Only the numbers differ.',
        feedback:['Circles are just the zero-eccentricity special case; lunar orbits can be elliptical.','','Orbits are curved, closed paths, not straight lines.','The Moon absolutely has gravity — about 1/6 of Earth’s surface gravity.'] } },
    { id:'a2', title:'A smaller world means slower orbits and easy escape',
      teach:[
        'The Moon is small — only about <b>1/81 of Earth’s mass</b>. Since it’s the mass of a body that sets how hard it pulls, the Moon’s gravity well is much <b>shallower</b> than Earth’s. Everything about orbiting it is gentler: you don’t need to move nearly as fast to stay in orbit, and it takes only a small shove to leave.',
        'The numbers tell the story. Skimming low around the Moon takes only about <b>1.63 km/s</b>, versus roughly 7.7 km/s down at Earth. And <b>escaping</b> the Moon entirely takes just <b>2.38 km/s</b>, against Earth’s 11.2. That’s why coming home from the lunar surface is comparatively cheap — a big reason the Moon looks so attractive as a staging point for deeper missions.',
      ],
      predict:'Before you read the numbers: the Moon is far lighter than Earth. Do you expect the speed needed to orbit it to be higher or lower than Earth’s ~7.7 km/s — and by a little or a lot?',
      do:'Note the readouts in the Low lunar orbit view: low-orbit speed ~1.63 km/s, lunar escape ~2.38 km/s. Compare each against the Earth values you met earlier (~7.7 and ~11.2 km/s).',
      observe:'because the Moon is much less massive than Earth, everything is gentler: you orbit low at ~1.6 km/s (vs ~7.7 at Earth) and escape at just ~2.4 km/s (vs ~11.2). That’s why leaving the Moon is comparatively cheap.',
      think:[
        'Roughly how many times faster do you have to go to orbit low around Earth than around the Moon?',
        'If leaving the Moon is this cheap, why might planners want to launch onward missions from the Moon rather than straight from Earth?',
        'What is it about the Moon — its size, its mass, or its spin — that actually sets these low speeds?',
      ],
      quiz:{ q:'Why is the speed needed to orbit (and escape) the Moon so much lower than for Earth?',
        opts:['The Moon spins faster','The Moon is far less massive, so its gravity is weaker — less speed is needed to orbit or escape',
              'The Moon has no atmosphere','The Moon is closer to the Sun'],
        a:1, why:'Correct — orbital and escape speeds scale with the body’s mass. The Moon is ~1/81 of Earth’s mass, so its gravity well is much shallower: ~1.6 km/s to orbit low, ~2.4 km/s to escape.',
        feedback:['Spin rate doesn’t set orbital speed — mass does.','','No atmosphere helps landing, but the speeds are set by gravity/mass.','Distance to the Sun is irrelevant to lunar orbit speed.'] } },

    // ---- PART B: the tug-of-war ----
    { id:'b1', title:'How far can you go and still orbit the Moon?',
      teach:[
        'Out here you’re never pulled by just one body. Earth and the Moon are <b>both</b> tugging on your spacecraft at the same time, and which one wins depends on where you sit. Every body owns a patch of space where its pull beats its neighbor’s — that patch is its <b>Hill sphere</b>.',
        'For the Moon, the Hill sphere reaches out to about <b>61,500 km</b> — and that’s the real outer limit on lunar orbits. Stay well inside it and the Moon’s grip is firm; drift toward its edge and Earth starts stealing the show, until an orbit around the Moon simply can’t hold together. Notice how modest that boundary is: only about <b>16% of the way</b> back to Earth.',
      ],
      predict:'Before you turn on the Hill sphere: do you think you could orbit the Moon from any distance, or is there a boundary out past which Earth’s pull takes over — and if so, roughly how far out?',
      do:'Switch to the <b>Earth–Moon system</b> zoom and turn on the <b>Moon’s Hill sphere</b> (the green wireframe around the Moon). Compare its size against the full Earth–Moon distance drawn across the view.',
      observe:'the Hill sphere (~61,500 km radius) is the Moon’s gravitational “territory.” Inside it, the Moon’s pull wins and you can orbit the Moon; outside, Earth’s pull takes over. It reaches only ~16% of the way to Earth.',
      think:[
        'Compared with the whole distance from Earth to the Moon, how big is the Moon’s territory?',
        'What do you think happens to a spacecraft that tries to orbit the Moon right at the edge of the Hill sphere?',
        'Why does it make sense that the lighter body — the Moon — gets the smaller territory?',
      ],
      quiz:{ q:'What sets the outer limit of orbits around the Moon?',
        opts:['The Moon’s atmosphere','The Moon’s Hill sphere (~61,500 km) — the region where the Moon’s gravity beats Earth’s',
              'The GEO belt','There is no limit — you can orbit the Moon from any distance'],
        a:1, why:'Correct — beyond the Moon’s Hill sphere (~61,500 km, about 16% of the way to Earth), Earth’s gravity dominates and an orbit around the Moon is no longer stable. Practical lunar orbits stay well inside it.',
        feedback:['The Moon has essentially no atmosphere.','','The GEO belt is a region around Earth, not a limit on lunar orbits.','There is a real limit — the Hill sphere — beyond which Earth wins the tug-of-war.'] } },
    { id:'b2', title:'Release something on the Earth–Moon line — which way?',
      teach:[
        'Somewhere on the line between Earth and the Moon there’s a single spot — the <b>balance point</b> — where an object released at rest on the — rotating — Earth–Moon line, keeping pace with it (like a bead threaded on a rod that sweeps around once a month), feels no net tug either way. You might guess it sits halfway. It doesn’t: it sits far out <b>toward the Moon</b>, at about <b>85% of the way</b> there. This is the <b>L1 Lagrange point</b>, where the Moon’s gravity <i>plus</i> the orbital (rotating-frame) effect of the whole system turning together exactly balance Earth’s pull — not the Moon’s gravity alone. (An object truly at rest, taking no part in that monthly turning, would find its pure-gravity balance a bit farther out — about 90% of the way.)',
        'That has a clean, testable consequence. Let go of an object at rest anywhere on the line and it rolls “downhill” toward whichever body is winning at that spot. Closer than 85% and it falls back to <b>Earth</b>; beyond 85% and it falls to the <b>Moon</b>. The midpoint, which feels like it ought to be neutral, is actually deep in Earth’s territory.',
      ],
      predict:'Before you release anything: if you let go of an object dead center between Earth and the Moon — at the 50% mark — which way do you think it will drift, toward Earth or toward the Moon?',
      do:[
        'Use the <b>Release on the Earth–Moon line</b> control. First release at <b>50%</b> (the midpoint) and watch which way it drifts.',
        'Now release at <b>90%</b> and compare — this one falls the other way.',
        'Try to bracket the balance point between them: is the flip nearer 80% or 90%?',
      ],
      observe:'the <b>balance point</b> is NOT the midpoint — it’s about <b>85% of the way to the Moon</b> (the L1 point, where the Moon’s gravity plus the orbital rotating-frame effect balance Earth’s pull). Release closer than 85% and it falls back to Earth; beyond 85% and it falls to the Moon.',
      think:[
        'At the 50% midpoint, which body wins the tug-of-war — and does that surprise you?',
        'Between your 50% and 90% releases, roughly where did the drift direction flip?',
        'Why does the Moon being so much lighter push the balance point out toward it, rather than toward Earth?',
      ],
      quiz:{ q:'You release an object at rest exactly halfway between Earth and Moon. Which way does it drift?',
        opts:['Toward the Moon','Toward the Earth — the balance point is ~85% of the way to the Moon, so the midpoint is well inside Earth’s territory',
              'It stays put forever','Straight up out of the plane'],
        a:1, why:'Correct — the balance point (the L1 point, where the Moon’s gravity plus the orbital rotating-frame effect balance Earth’s pull) sits far out toward the Moon, ~85% of the way. The midpoint is still firmly in Earth’s domain, so the object falls back toward Earth.',
        feedback:['The midpoint is inside Earth’s domain — it falls the other way.','','It’s not balanced at the midpoint; the balance point is much closer to the Moon.','Gravity pulls it along the line, not out of the plane.'] } },
    { id:'b3', title:'One level up: Earth vs. the Sun',
      teach:[
        'The tug-of-war idea doesn’t stop at the Moon — it <b>nests</b>. Zoom out one level and Earth itself is the small body, orbiting a far heavier <b>Sun</b>. So Earth has its own Hill sphere: its own territory where its pull beats the Sun’s.',
        'That boundary lies at the edge of Earth’s <b>Hill sphere</b>, about <b>1.5 million km</b> out — roughly four times the distance to the Moon. Inside it you orbit <b>Earth</b>; beyond it, the <b>Sun</b> takes over. It’s the exact same handoff you just watched between Earth and the Moon, only one rung up the ladder.',
      ],
      predict:'Before you switch views: you just saw the Earth–Moon handoff at the balance point. Do you expect a similar boundary between orbiting Earth and orbiting the Sun — and will it be closer in than the Moon, or much farther out?',
      do:'Switch to the <b>Sun–Earth system</b> zoom. Note the faint shell marking the edge of Earth’s <b>Hill sphere</b> (~1.5 million km). Flip back to the Earth–Moon view and then out again to feel how much larger this boundary is than the Moon’s orbit.',
      observe:'the same handoff happens between Earth and the Sun. Inside the edge of Earth’s Hill sphere (~1.5 million km) you orbit the Earth; beyond it, the Sun captures you.',
      think:[
        'How does Earth’s gravitational edge (~1.5 million km) compare with the Moon’s distance (~384,000 km)?',
        'Since the same tug-of-war repeats at every level, where does the Moon’s orbit sit — inside or outside Earth’s Hill sphere?',
        'What would it take for the Sun to “steal” a spacecraft away from Earth?',
      ],
      quiz:{ q:'What is the analogous boundary between “orbiting the Earth” and “orbiting the Sun”?',
        opts:['The GEO belt','The Moon’s orbit','The edge of Earth’s Hill sphere (~1.5 million km)','The edge of the atmosphere'],
        a:2, why:'Correct — the edge of Earth’s Hill sphere, at ~1.5 million km, is where the Sun’s pull begins to dominate. Inside it you orbit Earth; beyond it, the Sun.',
        feedback:['GEO is only ~36,000 km — far inside Earth’s domain.','The Moon (384,000 km) is still well inside Earth’s Hill sphere.','','The atmosphere ends a few hundred km up — nowhere near this boundary.'] } },

    // ---- PART C: reference frames (the core) — see the frames table above ----
    { id:'c1', title:'Earth-centred inertial (ECI): the Moon orbits Earth',
      teach:[
        'Now the heart of the module. A <b>reference frame</b> is nothing more than your choice of what to hold still while you watch everything else move — and that single choice can turn a baffling tangle of motion into a calm, obvious picture. There are four frames worth knowing (see the table above); you’ll meet them one at a time.',
        'Start with the most honest one: <b>Earth-centred inertial</b>, or <b>ECI</b>. It’s centered on Earth and it does <b>not</b> turn — it’s pinned to the distant stars. From here you see the Moon’s true motion with no tricks: it simply <b>orbits the Earth</b>, one lap a month. This is the default for ordinary Earth-orbit work, but for cislunar problems it has a catch — the Moon keeps sliding out from under you as you try to study it.',
      ],
      predict:'Before you speed up time: in a frame pinned to the fixed stars and centered on Earth, what do you think the Moon will do — hold still, or trace a path? If it moves, what shape?',
      do:'In the <b>Earth–Moon</b> zoom, select the <b>Earth-centred inertial (ECI)</b> frame and speed up time. Watch the Moon sweep a big circle around Earth against the fixed stars. Hold this picture in mind — you’ll switch frames next and watch the very same motion transform.',
      observe:'ECI is the “honest” physics frame — centered on Earth, not turning. The Moon plainly orbits Earth once a month. It’s the default for Earth-orbit work, but for cislunar problems the Moon keeps moving out from under you.',
      think:[
        'Why is ECI called the “honest” frame — what is it showing you that a rotating frame would hide?',
        'If you were tracking a spacecraft near the Moon in this frame, why would the Moon’s constant motion make your job harder?',
        'How long does the Moon take to make one full lap here?',
      ],
      quiz:{ q:'In the Earth-centred inertial (ECI) frame, what does the Moon do?',
        opts:['Hangs fixed in one spot','Orbits the Earth once a month, against the fixed stars',
              'Orbits the Sun','Falls straight toward Earth'],
        a:1, why:'Correct — ECI is centered on Earth and doesn’t rotate, so you see the Moon’s true motion: a monthly orbit around Earth. It’s physically fundamental but awkward when you want the Moon to hold still.',
        feedback:['That’s the rotating (synodic) frame — ECI shows the Moon moving.','','In ECI the Moon orbits Earth, not the Sun.','It doesn’t fall in — it’s in a stable monthly orbit.'] } },
    { id:'c2', title:'Earth–Moon rotating (synodic): the line stands still',
      teach:[
        'Here’s the trick that makes cislunar work manageable. Instead of holding the stars still, hold the <b>Earth–Moon line</b> still — spin your whole frame once a month so it keeps pace with the Moon. This is the <b>synodic</b>, or Earth–Moon rotating, frame, and it changes everything: the Moon now appears <b>frozen</b> in one place.',
        'Once the Moon stops moving, the geometry of the system snaps into view. The <b>Earth–Moon line and everything tied to it hold still</b>, so distances and directions along that line stop changing moment to moment — something you can actually see and reason about. This is <b>the</b> frame for designing transfers.',
      ],
      predict:'Before you switch: if your frame turns once a month so it keeps up with the Moon, what will the Moon appear to do? And what might that let you see that was impossible while it raced around?',
      do:'Select the <b>Earth–Moon rotating (synodic)</b> frame and speed up time. Flip back to ECI for a moment, then to synodic again — watch the Moon go from sweeping a circle to sitting perfectly still.',
      observe:'this frame turns once per month with the <b>Earth–Moon line</b>, so the Moon appears <b>frozen</b> in place. Now the Earth–Moon line and everything tied to it hold still, and the geometry stops changing moment to moment. This is THE frame for studying transfers.',
      think:[
        'What holds still in this frame that was moving in ECI — and why does that make transfers easier to plan?',
        'Why is the geometry easier to reason about once the Moon stopped moving?',
        'Nothing about the actual physics changed between ECI and here — so what exactly did you change?',
      ],
      quiz:{ q:'Why is the Earth–Moon rotating (synodic) frame the natural one for studying transfers?',
        opts:['It makes the satellites invisible','It turns with the Earth–Moon line so that line — and everything tied to it — holds still, instead of sweeping around',
              'It removes the Sun’s gravity','It’s the only frame that obeys physics'],
        a:1, why:'Correct — the frame co-rotates with the Earth–Moon line, so that line and everything fixed to it stand still — exactly what you want for designing transfers.',
        feedback:['Satellites stay visible — the point is that the Earth–Moon line holds still.','','It doesn’t remove any gravity; it just co-rotates.','All frames obey physics; rotating ones just add a steady turn.'] } },
    { id:'c3', title:'Moon-centred inertial (MCI): the Earth orbits the Moon',
      teach:[
        'Motion is always relative to what you pick as your center. In ECI you centered on Earth and watched the Moon go around. Now do the mirror image: center on the <b>Moon</b> instead, still without turning. This is <b>Moon-centred inertial</b>, or <b>MCI</b>.',
        'The result can feel upside-down at first: the <b>Earth</b> now appears to orbit the <b>Moon</b>, once a month. It’s the exact same relative motion you saw in ECI — the gap between the two bodies opens and closes identically — just seen from the other body. This is the natural frame for problems about <b>arriving at the Moon</b>, where the Moon is the thing you want centered.',
      ],
      predict:'Before you switch: you saw the Moon orbit Earth in ECI. If you now plant your camera on the Moon instead and don’t rotate, what do you think the Earth will appear to do?',
      do:'Select the <b>Moon-centred inertial (MCI)</b> frame. Now the Moon is centered and NOT turning — watch what the Earth does. Then flip back to ECI and compare: the relative motion is identical, only the center moved.',
      observe:'centering on the Moon (without co-rotating) flips the picture: the <b>Earth appears to orbit the Moon</b> once a month. It’s the exact same relative motion as ECI, just seen from the other body — the natural frame for arriving-at-the-Moon problems.',
      think:[
        'How is MCI just ECI “seen from the other side”?',
        'In this frame the Earth is NOT fixed in the sky — it circles. Which frame would make Earth hang still instead?',
        'For a spacecraft trying to slip into lunar orbit, why is centering on the Moon the helpful choice?',
      ],
      quiz:{ q:'In the Moon-centred inertial (MCI) frame, how does the Earth appear to move?',
        opts:['It hangs fixed in the sky','It appears to orbit the Moon once a month — the same relative motion as ECI, seen from the Moon',
              'It falls into the Moon','It orbits the Sun once a day'],
        a:1, why:'Correct — motion is relative. Centering on the Moon (and not rotating) makes the Earth trace a monthly circle around the Moon, mirroring the Moon’s ECI orbit around Earth. Same physics, opposite vantage point.',
        feedback:['In MCI (inertial) the Earth circles the Moon monthly; it doesn’t hang fixed.','','It’s in a stable relative orbit, not falling in.','The monthly period is the Moon’s orbit, and it’s around the Moon here, not the Sun.'] } },
    { id:'c4', title:'ECL-EMBR: the barycentric rotating frame (where the Lagrange points live)',
      teach:[
        'The fourth frame is the one professionals use for <b>cislunar</b> work. Its full name — <b>ECL-EMBR</b> — spells out its three choices: it uses the <b>ECL</b>iptic (the plane the Earth and Moon orbit in) as its reference plane; it is centered on the <b>E</b>arth–<b>M</b>oon <b>B</b>arycenter; and it is <b>R</b>otating, turning once a month with the Earth–Moon line.',
        'The key new idea is the <b>barycenter</b>: Earth and Moon don’t sit still while the other circles — they <b>both orbit their shared center of mass</b>. Because Earth outweighs the Moon ~81:1, that point is only ~4,670 km from Earth’s center (actually <i>inside</i> the Earth). In reality it is <b>Earth that swivels</b> around that point in a small circle once a month. The simulator keeps Earth pinned at the center so you can see everything else, and marks the barycenter with an orange cross (its offset exaggerated for visibility) — so <b>picture</b> the wobble rather than watch for it. Center on the barycenter and co-rotate, and <b>both bodies freeze</b> on the axis.',
        'Why bother? Because holding the barycenter and the line still is exactly what makes the <b>five Lagrange points sit motionless</b> — the balance points you met earlier stop drifting and become fixed places you can park at. This is the stage on which all of Module 6 (Lagrange points, halo orbits) is built. The panel also draws two reference disks — the <b>ecliptic</b> and Earth’s <b>equator</b>, tilted ~23.4° apart — a reminder that cislunar space is referenced to the ecliptic, not the equator we used for Earth orbits.',
      ],
      predict:'Before you switch: if you center on the point that Earth and Moon BOTH circle (their barycenter) and turn with the line, what will the Earth appear to do — and what happens to the balance/Lagrange points?',
      do:'Select the <b>ECL-EMBR</b> frame in the Earth–Moon zoom. Find the marked <b>barycenter</b> (the orange cross, drawn exaggerated for visibility): both bodies hold their places on the axis. Remember it is really <b>Earth</b> that swivels around that cross once a month — the sim keeps Earth pinned, so picture that wobble. Note the two tilted reference planes — the ecliptic and the equator.',
      observe:'this frame centers on the Earth–Moon barycenter and co-rotates with the line, so <b>both</b> Earth and Moon are frozen on the axis (in reality Earth traces a small monthly circle about the barycenter — the sim keeps Earth pinned, so picture it). This is the frame in which the Lagrange points stay put — the natural stage for cislunar orbits.',
      think:[
        'In reality Earth traces a small monthly circle about the barycenter. Reason it out: why can’t Earth sit perfectly still while the Moon circles it — what is Earth itself orbiting?',
        'The synodic frame (Frame 2) also froze the Earth–Moon line. What does centering on the barycenter add that Earth-centering did not?',
        'Why must the Lagrange points be motionless in THIS frame but drift in ECI?',
      ],
      quiz:{ q:'In the ECL-EMBR (barycentric rotating) frame, what is special about the view?',
        opts:['Only the Moon is frozen; Earth circles it',
              'Both Earth and Moon are frozen on the axis (Earth sitting just off-center from the barycenter), and the Lagrange points hold still',
              'Everything spins rapidly','The Sun is centered and the planets orbit it'],
        a:1, why:'Correct — centering on the shared barycenter and co-rotating with the line freezes BOTH bodies. Earth sits just off-center (in reality it swivels around the barycenter, ~4,670 km inside it, once a month), and it is precisely the frame in which the five Lagrange points become fixed points — the foundation for Module 6.',
        feedback:['Both bodies orbit the barycenter, so both freeze here — not just the Moon.','','It is a rotating frame chosen to make bodies and Lagrange points hold STILL, not spin.','This is the Earth–Moon system, centered on their barycenter — not a heliocentric frame.'] } },

    { id:'c5', title:'See all four frames at once',
      teach:[
        'You’ve now met all four frames one by one. This is the payoff view: put them <b>side by side</b> and watch the identical motion tell four completely different stories at the same instant. Same Moon, same satellites, same clock — the <i>only</i> thing that differs between panels is the frame.',
        'This is the whole lesson made visible. The Moon can’t “really” be both frozen and sweeping a huge circle — yet here it is doing both, in two panels, at once. That’s the point: none of the frames is more true than the others. Motion only means something <b>relative to the frame you chose</b>, and the skill is picking the frame that makes your particular problem simple.',
      ],
      predict:'Before you open the compare view: knowing what each frame does, predict what the Moon will look like in each of the four panels — moving or still, and around what.',
      do:'Click <b>Compare all 4 frames at once (2×2)</b>. The same Moon, satellites, and clock play in every panel — only the <b>frame</b> differs. Pan/zoom/rotate each panel independently, and use the single time control (<kbd>,</kbd>/<kbd>.</kbd>) to speed all four together.',
      observe:'the identical motion looks completely different per frame: in <b>ECI</b> the Moon sweeps a big circle around Earth; in <b>synodic</b> the Moon is frozen and the stars wheel behind it; in <b>MCI</b> the Earth circles the Moon; in <b>ECL-EMBR</b> you centre on the Earth–Moon barycenter and co-rotate, so both bodies freeze and the Lagrange points hold still. Same physics, four stories.',
      think:[
        'Is any one of the four panels “more correct” than the others? Why or why not?',
        'For planning a transfer between Earth and the Moon, which panel would you work in — and for a lunar landing?',
        'Given all four share one clock and one set of objects, what single choice is different between any two panels?',
      ],
      quiz:{ q:'In the 2×2 compare view, why does the Moon look motionless in the synodic (rotating) panel but sweep a big circle in the ECI panel — at the same moment?',
        opts:['The panels are running at different speeds',
              'They share one clock and one set of objects — only the reference frame differs, and the synodic frame turns with the Moon so it appears fixed',
              'The rotating panel has paused the Moon','The ECI panel is zoomed out further'],
        a:1, why:'Correct — all four panels show the identical dynamics on the same clock; the ONLY difference is what each frame holds still. The rotating frame turns once per month with the Earth–Moon line, so the Moon sits frozen there while, in the inertial panel, that same Moon visibly orbits. That’s the whole lesson: motion is relative to your chosen frame.',
        feedback:['They share one global clock — the speeds are identical.','','Nothing is paused; the rotating frame just co-rotates with the Moon.','Zoom is independent per panel, but that’s not why the Moon’s motion differs — the frame is.'] } },

    // ---- PART D: the Moon itself ----
    { id:'d1', title:'The Moon is just another Earth satellite',
      teach:[
        'Step back and look at the Moon itself with the eyes you built in earlier modules. For all its size and history, the Moon is just <b>another satellite of Earth</b>, obeying the very same rules as any spacecraft you’ve flown. It’s bound in an orbit; it has a shape, a tilt, and a period.',
        'The specifics: its orbit is <b>slightly elliptical</b> (eccentricity about 0.055 — nearly circular, but not quite), <b>tilted about 5°</b> to the ecliptic, and it takes <b>one month</b> (~27.3 days) to go around. It just happens to be enormous and very far out — the biggest object in all of xGEO.',
      ],
      predict:'Before you turn it on: knowing the Moon is “just another satellite,” do you expect its orbit to be a perfect circle or slightly elliptical like most orbits you’ve seen — and roughly how long for one lap?',
      do:'In the Earth–Moon zoom, turn on the Moon’s orbit around Earth and watch it over a month. Look for how far it departs from a perfect circle.',
      observe:'the Moon obeys the same rules as any satellite: a slightly elliptical orbit (eccentricity ~0.055) with a period of one month (~27.3 days). In reality it is also tilted about 5° to the ecliptic — a fact the sim flattens for clarity. It’s the biggest thing in xGEO.',
      think:[
        'The Moon’s orbit is only slightly elliptical (e≈0.055) — does it look noticeably egg-shaped, or nearly round, to your eye?',
        'How does the Moon’s ~1-month period compare with the orbits you studied around Earth in earlier modules?',
        'What makes the Moon special among Earth’s satellites — its rules, or just its size and distance?',
      ],
      quiz:{ q:'The Moon’s own orbit around Earth is best described as…',
        opts:['A perfect circle in the equatorial plane','A slightly elliptical orbit, inclined ~5° to the ecliptic, with a ~1-month period',
              'A polar orbit','Fixed in place — the Moon doesn’t really orbit'],
        a:1, why:'Correct — the Moon is a satellite like any other: e≈0.055 (slightly elliptical), inclined ~5° to the ecliptic, one lap per month. It just happens to be very large and very far out.',
        feedback:['It’s slightly elliptical and tilted to the ecliptic, not a perfect equatorial circle.','','It’s not polar — it’s within ~5° of the ecliptic.','The Moon very much orbits — once every ~27 days.'] } },
    { id:'d2', title:'Tidal locking: the same face always toward Earth',
      teach:[
        'Here’s something you can check with your own eyes any clear night: we always see the <b>same face</b> of the Moon. The far side never turns toward us. That’s not a coincidence, and it’s not because the Moon doesn’t spin — it’s because the Moon is <b>tidally locked</b>.',
        'Tidal locking means the Moon spins on its axis exactly <b>once per orbit</b>. Its “day” and its “year” are the same length, so as it swings around Earth it keeps turning just enough to hold the same hemisphere facing us — the “near side,” with the “far side” always turned away. One myth to bury: the far side is <b>not</b> the “dark side.” It gets just as much sunlight; it’s simply always facing away from Earth. (Exactly <i>why</i> the locking happens is beyond our scope — see the resources.)',
      ],
      predict:'Before you watch: as the Moon travels around Earth, do you think it keeps the same face toward us because it doesn’t spin at all, or because its spin is somehow synced to its orbit?',
      do:'Watch the Moon over an orbit in the Earth–Moon rotating frame — the same face stays toward Earth. Now switch to the <b>Moon-centred inertial (MCI)</b> frame, which rides along with the Moon: follow a surface feature and notice the Moon really is turning, just once per lap.',
      observe:'the Moon is <b>tidally locked</b>: it rotates exactly once per orbit, so one hemisphere always faces Earth (the “near side”) and one always faces away (the “far side”). Why this happens is beyond our scope — see the tidal-locking resource.',
      think:[
        'Does the Moon rotate or not? What does “once per orbit” really mean here?',
        'If the far side gets just as much sunlight as the near side, why do people call it the “dark side”?',
        'What would we see from Earth if the Moon did NOT spin at all as it orbited?',
      ],
      quiz:{ q:'Why do we always see the same face of the Moon?',
        opts:['The Moon doesn’t rotate at all','It’s tidally locked — it rotates exactly once per orbit, so the same face always points at Earth',
              'Earth blocks the other side','The far side is always dark'],
        a:1, why:'Correct — tidal locking means the Moon’s spin period equals its orbital period, so the same hemisphere always faces us. (The far side is NOT always dark — it gets just as much sunlight; it’s just always facing away from Earth.)',
        feedback:['It does rotate — once per orbit, which is exactly why one face stays toward us.','','Earth doesn’t block it; the Moon’s own rotation is synced to its orbit.','The far side gets plenty of sunlight — “far side” is not “dark side.”'] } },
    { id:'d3', title:'Three tilted planes',
      teach:[
        'You might expect a solar or lunar eclipse every month — after all, the Moon laps Earth monthly, passing between us and the Sun and then swinging behind us. But we don’t get them monthly, and the reason is that the relevant orbits <b>don’t lie flat in the same plane</b>.',
        'There are <b>three planes</b> here, all tilted against one another: Earth’s <b>equator</b>, the <b>ecliptic</b> (the plane of Earth’s orbit around the Sun), and the <b>Moon’s orbit</b> (tilted about 5° to the ecliptic). Because they don’t line up, the Sun, Earth, and Moon usually miss exact alignment — the Moon passes a little above or below. Only when the Moon happens to cross the ecliptic at just the right moment do the three snap into line and give us an eclipse.',
      ],
      predict:'Before you compare the planes: if the Moon passes between Earth and the Sun every month, why do you think we don’t get an eclipse every single month? Take a guess before you look.',
      do:'Select the <b>ECL-EMBR</b> frame, which draws two reference disks: the <b>ecliptic</b> and Earth’s <b>equator</b>, tilted 23.4° apart (the tilt you met in Module 2). Rotate the view edge-on to see how far apart those two planes sit. The Moon’s own orbit adds a further ~5° tilt to the ecliptic — the sim draws it flat for clarity, so take that one as a taught fact.',
      observe:'three planes are all tilted with respect to each other: Earth’s <b>equator</b>, the <b>ecliptic</b> (Earth’s orbit around the Sun), and the <b>Moon’s orbit</b>. Because they don’t line up, the Sun, Earth, and Moon only occasionally align well enough for an eclipse.',
      think:[
        'If all three planes lined up perfectly, how often would eclipses happen?',
        'A ~5° tilt sounds tiny — why is it enough to prevent a monthly eclipse?',
        'What has to be true about the Moon’s position for the Sun, Earth, and Moon to finally line up?',
      ],
      quiz:{ q:'Why don’t we get a solar and lunar eclipse every single month?',
        opts:['Eclipses are random','The Moon’s orbit is tilted ~5° to the ecliptic, so usually the Sun, Earth, and Moon don’t line up exactly — alignment only happens occasionally',
              'The Moon isn’t always full','Clouds block them'],
        a:1, why:'Correct — because the Moon’s orbital plane is tilted ~5° from the ecliptic, the three bodies usually miss exact alignment; only when the Moon crosses the ecliptic at the right time do we get an eclipse. The tilt of the planes is the key.',
        feedback:['They’re predictable, set by the geometry of the tilted planes.','','Phase matters, but the deeper reason is the ~5° tilt preventing monthly alignment.','Clouds affect visibility locally, not whether an eclipse occurs.'] } },

    // ---- PART E: defining xGEO ----
    { id:'e1', title:'What exactly is xGEO?',
      teach:[
        'This whole course has been climbing outward — LEO, then the MEO home of GPS, then the GEO belt. <b>xGEO</b> is the next region out, and it’s the one this module has been building toward. The name is shorthand for “extended GEO”: the space that lies <b>beyond the GEO belt</b> (~36,000 km) but is <b>still held by Earth</b>, all the way out to the edge of Earth’s Hill sphere at ~1.5 million km.',
        'It’s a huge, mostly empty volume — and the <b>Moon</b>, at 384,400 km, sits squarely inside it. Until recently almost nothing operated out here, so it’s sparsely tracked and hard to monitor. That’s exactly why it has become strategically important: cislunar space is the newly contested high ground, and knowing where its boundaries lie is the foundation for everything that follows.',
      ],
      predict:'Before you zoom around: based on the tug-of-war and Hill spheres you’ve seen, where would you place the two boundaries of xGEO — its inner edge and its outer edge?',
      do:'Zoom between the Earth–Moon and Sun–Earth views and note where the GEO belt, the Moon, and the edge of Earth’s Hill sphere sit. Confirm for yourself that the Moon falls between the inner edge (GEO) and the outer edge (Earth’s gravitational edge).',
      observe:'<b>xGEO</b> (“extended GEO,” or the cislunar region) is space that is <b>farther from Earth than the GEO belt (~36,000 km) but still bound to Earth</b> — out to the edge of Earth’s Hill sphere at ~1.5 million km. The Moon (384,400 km) sits squarely inside it. It’s the newly-contested region this whole course has been building toward.',
      think:[
        'What marks the inner edge of xGEO, and what marks the outer edge?',
        'Why does the Moon count as being “in xGEO,” while a GPS satellite does not?',
        'Why would a region this vast and this empty be hard to keep watch over?',
      ],
      quiz:{ q:'How is “xGEO” (cislunar) space best defined?',
        opts:['Anything above the atmosphere','The region beyond the GEO belt (~36,000 km) but still within Earth’s gravitational grip (out to the edge of Earth’s Hill sphere, ~1.5 million km)',
              'Only the space around the Moon','Everything between Earth and the Sun'],
        a:1, why:'Correct — xGEO is beyond the crowded GEO belt yet still bound to Earth, reaching out past the Moon to the edge of Earth’s Hill sphere. It’s vast, sparsely monitored, and increasingly strategically important.',
        feedback:['That would include LEO and GEO themselves — xGEO is specifically beyond GEO.','','It includes lunar space but is broader than just around the Moon.','It stops at the edge of Earth’s Hill sphere, not all the way to the Sun.'] } },

    // ---- PART F: flying to the Moon ----
    { id:'f1', title:'Lead the Moon like a duck hunter',
      teach:[
        'Reaching the Moon is not a matter of pointing at it and firing. The trip takes <b>several days</b>, and the Moon never stops moving — it slides along its orbit at about <b>13° per day</b> the whole time you’re coasting out. Aim at where the Moon <b>is</b> and you’ll sail out to that spot to find it long gone.',
        'So you do what a duck hunter does: you <b>lead the target</b>. You fire into a big transfer ellipse whose high point (apogee) reaches the Moon’s distance, and you aim that apogee at the empty spot where the Moon <b>will be</b> when you arrive. Too little lead and you get there early, before the Moon shows up; too much and the Moon has already swept past. There’s a right lead angle that puts you and the Moon at the same place at the same time.',
      ],
      predict:'Before you fire: the trip out takes a few days and the Moon keeps moving. Do you think you should aim at where the Moon is now, ahead of it, or behind it — and what happens if you aim right at it?',
      do:'Click <b>set up a LEO→Moon transfer</b>, drag the lead-angle slider, then press <b>🔥 launch (burn trans-lunar injection)</b> at different lead angles. (The demo plays in the ECI frame, because the “lead the Moon” aiming reads most naturally against the fixed stars.) Try a small lead first and watch the Moon arrive late; then a large lead and watch it arrive early; then hunt for the lead that lands you together at apogee.',
      observe:'the transfer takes a few days, and the Moon keeps moving the whole time. So you don’t aim at where the Moon <i>is</i> — you aim at where it <i>will be</i> when you coast out to apogee. Too little lead and the Moon hasn’t arrived; too much and it’s already gone by.',
      think:[
        'When you aimed straight at the Moon’s current spot, where was the Moon by the time you coasted out to apogee?',
        'How did arriving “too early” look different from arriving “too late”?',
        'The Moon moves ~13°/day and the trip takes a few days — roughly how far ahead does that mean you must aim?',
      ],
      quiz:{ q:'To reach the Moon, where do you aim your transfer orbit’s high point (apogee)?',
        opts:['At the Moon’s current position','At the point where the Moon WILL be when you arrive, a few days later — you “lead” it like a moving target',
              'Directly away from the Moon','It doesn’t matter — the Moon’s gravity pulls you in'],
        a:1, why:'Correct — because the trip takes days and the Moon moves ~13°/day, you launch toward the empty spot where the Moon will arrive just as you reach apogee. Leading the target is the essence of a lunar transfer.',
        feedback:['Aim where it is now and it will have moved on by the time you arrive.','','You aim ahead of the Moon along its orbit, not away from it.','You must arrive close enough for its gravity to matter — that requires leading it.'] } },
    { id:'f2', title:'A lunar transfer in two burns',
      teach:[
        'That flight you just flew is really the <b>same two-step maneuver</b> you learned in Module 4, just scaled all the way out to the Moon. Big trips in space almost always come down to two well-timed shoves with a long, free coast in between.',
        'Step one is the <b>trans-lunar injection</b>: a burn from low Earth orbit that raises your apogee out to the Moon’s distance, sending you on the days-long coast. Step two, on arrival, is the <b>lunar-orbit insertion</b>: a braking burn that sheds enough speed for the Moon to <b>capture</b> you. Skip that second burn and the Moon’s gravity just whips you around and flings you back — a flyby, not an orbit. You need both.',
      ],
      predict:'Before you think it through: getting from low Earth orbit into orbit around the Moon — do you think that takes one burn, two, or none at all? And what would happen if you only did the first one?',
      do:'Think about the transfer you just flew as a two-step maneuver (recall the macro-maneuver recipe from Module 4). Trace in your mind where each burn happens: one to leave Earth orbit, one to arrive at the Moon.',
      observe:'reaching lunar orbit is the same two-step idea from Module 4, scaled up: (1) a <b>trans-lunar injection</b> burn from low Earth orbit raises your apogee all the way out to the Moon’s distance; (2) on arrival, a <b>lunar-orbit-insertion</b> burn slows you so the Moon captures you. Miss either and you fly past.',
      think:[
        'Where along the trip does each of the two burns happen — and what does each one do?',
        'If you fired the first burn but skipped the second, what would your spacecraft do at the Moon?',
        'How is this just the Module-4 two-step recipe, scaled up to the Moon?',
      ],
      quiz:{ q:'Getting from low Earth orbit into orbit around the Moon takes (at least) how many burns, and why?',
        opts:['One — just point at the Moon and thrust the whole way',
              'Two — a trans-lunar injection to raise apogee to the Moon, then a capture (insertion) burn to slow down so the Moon holds you',
              'Zero — Earth’s gravity delivers you automatically','Three or more, always'],
        a:1, why:'Correct — it’s the Module-4 two-step recipe scaled to the Moon: burn to send apogee out to lunar distance, coast (leading the Moon), then brake into lunar orbit. Without the capture burn you’d just swing past and come back.',
        feedback:['Continuous thrust the whole way isn’t how chemical transfers work — they’re impulsive burns with a long coast.','','Gravity alone gives a flyby, not capture — you must brake to be captured.','Two impulsive burns is the basic case; extras are only for corrections.'] } },
  ],

  exam: [
    { q:'What decides whether an object orbits the Moon or the Earth?',
      opts:['Whichever body is physically larger',
            'Whether the object is above or below the GEO belt',
            'Whether it sits inside the Moon’s <b>Hill sphere</b> (~61,500 km) — the zone where the Moon’s pull beats Earth’s',
            'Nothing — an object can orbit either body from any distance'],
      a:2, why:'Correct — inside the Moon’s Hill sphere the Moon’s gravity dominates and you orbit the Moon; outside it, Earth wins the tug-of-war.',
      feedback:['Size alone doesn’t decide it — what matters is whose gravity dominates at that spot, i.e. the Hill sphere.',
                'The GEO belt is a region around Earth, unrelated to the Earth–Moon handoff.',
                '',
                'There is a real boundary — the Hill sphere — beyond which Earth takes over.'] },
    { q:'The Earth–Moon balance point (the L1 point) sits about 85% of the way to the Moon. Why isn’t it at the midpoint?',
      opts:['Because the Moon is far lighter than Earth, so its gravity plus the orbital (rotating-frame) effect balance Earth’s pull far out toward the Moon (at L1)',
            'Because the Moon is heavier than Earth',
            'Because the Moon spins quickly',
            'It actually is at the midpoint'],
      a:0, why:'Correct — at L1 the Moon’s gravity plus the orbital rotating-frame effect balance Earth’s much stronger pull, and because the Moon is so much lighter that balance lands far out toward it, at ~85% of the way rather than halfway.',
      feedback:['',
                'It’s the opposite — the Moon is much lighter, which is what pushes the balance point out toward it.',
                'Spin rate doesn’t set the balance point; the mass difference and the orbital effect do.',
                'It’s about 85% of the way to the Moon, well past the midpoint.'] },
    { q:'Which best describes <b>xGEO</b> (cislunar) space?',
      opts:['Any orbit above the atmosphere',
            'Only the region immediately around the Moon',
            'Everything between Earth and the Sun',
            'The region beyond the GEO belt (~36,000 km) but still bound to Earth, out to the edge of Earth’s Hill sphere (~1.5 million km)'],
      a:3, why:'Correct — xGEO is beyond the crowded GEO belt yet still within Earth’s grip, reaching out past the Moon to the edge of Earth’s Hill sphere.',
      feedback:['That would include LEO and GEO themselves — xGEO is specifically beyond GEO.',
                'It includes lunar space but is far broader than just around the Moon.',
                'It stops at the edge of Earth’s Hill sphere, well short of the Sun.',
                ''] },
    { q:'The four reference frames differ by two choices. What are those two choices?',
      opts:['Their on-screen color and size',
            'What the frame is <b>centered on</b> (Earth, the Moon, or the pair’s barycenter) and <b>whether it turns with the Earth–Moon line</b>',
            'How fast time runs and how far you zoom in',
            'Which country operates the spacecraft'],
      a:1, why:'Correct — each frame is set by what it centers on and whether it co-rotates with the Earth–Moon line; that choice fixes what holds still and what moves.',
      feedback:['Frames aren’t defined by how they look.',
                '',
                'Time speed and zoom are viewing options — they don’t define the frame.',
                'The operator has nothing to do with the physics frame.'] },
    { q:'A trip to the Moon takes a few days. Where do you aim your transfer orbit’s high point (apogee)?',
      opts:['Straight at where the Moon is right now',
            'Directly away from the Moon',
            'At the empty spot where the Moon <i>will be</i> when you arrive — you lead it like a moving target',
            'It doesn’t matter; the Moon’s gravity will grab you from anywhere'],
      a:2, why:'Correct — the Moon moves ~13°/day, so you aim ahead of it, at where it will arrive just as you coast out to apogee.',
      feedback:['Aim where it is now and it will have moved on by the time you arrive.',
                'You aim ahead of the Moon along its orbit, not away from it.',
                '',
                'You must arrive close enough for its gravity to matter — and that requires leading it.'] },
  ],
};
